### ISSUE TITLE
h264_vaapi: segmentation fault (core dumped) when the height is small

### ISSUE THREAD

**Issue by nacknime-official** [ammen99/wf-recorder#103]
```
  ➜  ~ wf-recorder -g "$(slurp)" -f waybar.mp4 -c h264_vaapi -d /dev/dri/renderD128
Adjusted geometry: 0,0 1920x76
selected region 0 0 1920 76
[h264_vaapi @ 0x7f7620001b40] No quality level set; using default (20).
Output #0, mp4, to 'waybar.mp4':
    Stream #0:0: Unknown: none (h264_vaapi)
[mp4 @ 0x7f7620000d40] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[1]    95626 segmentation fault (core dumped)  wf-recorder -g "$(slurp)" -f waybar.mp4 -c h264_vaapi -d /dev/dri/renderD128
```

another height

```
➜  ~ wf-recorder -g "$(slurp)" -f waybar.mp4 -c h264_vaapi -d /dev/dri/renderD128
Adjusted geometry: 0,0 1920x300
selected region 0 0 1920 300
[h264_vaapi @ 0x7f49ec001b40] No quality level set; using default (20).
Output #0, mp4, to 'waybar.mp4':
    Stream #0:0: Unknown: none (h264_vaapi)
[mp4 @ 0x7f49ec000d40] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
^C%                                                                                                     
 ➜  ~  
```

**Comment by soreau** [comment]
I am able to record a 4px height video with vaapi using `wf-recorder -g "0,0 1920x4" -t -c h264_vaapi -d /dev/dri/renderD128`. Are you using wf-recorder latest git or a released version? Are you able to get a backtrace with gdb?

**Comment by ammen99** [comment]
I can also record with geometry "0,0 1920x30", seems like this is a bug in your setup (using intel drivers here, if that matters). Have you tried recording with this geometry under X11 via the `ffmpeg` command? I assume it is possible, but I don't know how exactly. If not possible, just try encoding any video with said resolution via ffmpeg.

**Comment by nacknime-official** [comment]
I don't know, but... it has fixed itself.
Firstly, when I ran wf-recorder with arg -`f waybar.mp4` then I got Segmentation fault. Then I tried change name of the output filename to `test.mp4` and choice the size on 1920x20 and... it worked!
Then I tried change the filename `waybar.mp4` again and it worked.
I don't know what was it, maybe my SSD are going to die, I'm gonna run fsck...
