### ISSUE TITLE
av_hwdevice_get_hwframe_constraints is not freed

### ISSUE THREAD

**Issue by H-M-H** [ammen99/wf-recorder#104]
A call to `av_hwframe_constraints_free` is missing after allocating: https://github.com/ammen99/wf-recorder/blob/87c2b9be5e70d192691f83b61e052915a0d91823/src/frame-writer.cpp#L49

**Comment by soreau** [comment]
It would seem that you are correct. Care to submit a PR?

**Comment by H-M-H** [comment]
Sure have a look at #105 .
