### ISSUE TITLE
Version command line flag

### ISSUE THREAD

**Issue by muniter** [ammen99/wf-recorder#108]
Hey! Thank you for this great little software. Really enjoy it for my workflow. I have a feature request. It would be nice to get the version of the program as usual: `wl-recorder --version` but at the moment in the build I have It doesn't work, had to see installed packages with apt, to check the version! I think it would be useful, and It's pretty much expected!. The version number could also be printed at the top when `wl-recorder --help` is run.

According to the Ubuntu repositories I'm on `0.2-1build1`

**Comment by ammen99** [comment]
Thanks for the good suggestion, I have added an option `-v / --version` which outputs the version, git commit and build date.
