### ISSUE TITLE
failed to create display: No such file or directory

### ISSUE THREAD

**Issue by mjuarezm** [ammen99/wf-recorder#110]
I've followed this instructions from the Arch wiki: https://wiki.archlinux.org/index.php/Screen_capture#Screensharing
 
I'm able to create the device but `wf-recorder` does not seem to detect it correctly. Any ideas?

Output of `v4l2-ctl --list-devices`:
> WfRecorder (platform:v4l2loopback-000):
>         /dev/video2

Output of `wf-recorder --muxer=v4l2 --codec=rawvideo --file=/dev/video2`:
> failed to create display: No such file or directory

Output of `echo $DISPLAY `
> :1

It's difficult to debug the problem because `wf-recorder` does not have any logging options.

**Comment by soreau** [comment]
Is WAYLAND_DISPLAY set?

**Comment by mjuarezm** [comment]
no, it's not. I'm using x11

**Comment by soreau** [comment]
As the README states, "wf-recorder is a utility program for screen recording of wlroots-based compositors". This means it isn't designed to work with X.

**Comment by mjuarezm** [comment]
my fault. sorry for that. thanks for the help!
