### ISSUE TITLE
Keep slurp until record is finished

### ISSUE THREAD

**Issue by timsofteng** [ammen99/wf-recorder#116]
Hello. I'm using wf-recorder with slurp together. Is it any way to keep slurp background until record will stop?

**Comment by ammen99** [comment]
Hi, I don't think so, slurp exits as soon as the region is selected

**Comment by timsofteng** [comment]
> Hi, I don't think so, slurp exits as soon as the region is selected

It's sad. I suppose this feature would be useful.

**Comment by WhyNotHugo** [comment]
Why do you want to keep `slurp` running? Once you've selected a region, its job if finished; what are you trying to achieve?

**Comment by kode54** [comment]
Maybe they want something highlighting the selected region for the duration of the recording.

**Comment by ammen99** [comment]
Anyway, this is not a feature that should be implemented in wf-recorder.

**Comment by WhyNotHugo** [comment]
> Maybe they want something highlighting the selected region for the duration of the recording.

If this is the case, just run `slurp` during the recording, you can run a second copy and its highlighting will be recorded.
