### ISSUE TITLE
Help for --audio might be incorrect. Shouldn't it be `pactl list sources`?

### ISSUE THREAD

**Issue by cauebs** [ammen99/wf-recorder#119]

**Comment by soreau** [comment]
Yes I think [it](https://github.com/ammen99/wf-recorder/blob/master/src/main.cpp#L532) should be `pacmd list-sources | grep "name:"` like is is in the [wiki](https://github.com/ammen99/wf-recorder/wiki).

**Comment by cauebs** [comment]
You're right, thanks. Hadn't checked the wiki. I opened a very simple PR just to speed things up.
