### ISSUE TITLE
No sound in recording

### ISSUE THREAD

**Issue by kaihendry** [ammen99/wf-recorder#12]
Doesn't appear to be any sound with the recording. No source in `pavucontrol`.

**Comment by ammen99** [comment]
Yes, sound capturing isn't implemented.

**Comment by kaihendry** [comment]
I used your program to produce https://www.youtube.com/watch?v=rTeLIFru-Eg

Would be a lot easier to sync if it had audio. Thank you.

**Comment by ammen99** [comment]
I'll see what I can do.

**Comment by ammen99** [comment]
@kaihendry Hi again, I have done some work in the `audio-wip` branch. It would be good if more people could test it before I merge. If you want to try it, use the `-a` option to enable audio.

There is however a "strange" issue: if there is no audio being played when the recorder is started, the audio stream gets ~1 second behind the video stream. There seem to be no sync problems if an audio is already playing when starting wf-recorder. It would be good if you could also confirm this behavior.

**Comment by ammen99** [comment]
Another update: I now resolved the problems I had. You can record the default audio device (in my case the mic) with just the `-a` flag, and you can also select the device to capture from with either `-a<devname>` or `--audio=<devname>`, where devname can be found from `pactl list sources`

**Comment by kaihendry** [comment]
https://s.natalian.org/2019-03-28/test-vaapi.mkv
https://s.natalian.org/2019-03-28/no-vaapi.mp4

Seems to work! Well done. `-a` alone uses the default which is good. :bowing_man:

**Comment by ammen99** [comment]
Thanks for testing!

**Comment by pvalena** [comment]
I've just spent several hours making this wrong, and only after reading this I did come to realization there musn't be a space between `-a` and the device. Which is not what the `--help` says:

```
-a, --audio [DEVICE]
```
