### ISSUE TITLE
How to achieve best quality?

### ISSUE THREAD

**Issue by rhysperry111** [ammen99/wf-recorder#122]
Hi, I am trying to use `wf-recorder` to achieve high quality desktop capture. The problem is, it looks like.... ass. I have specified `--codec libx264 -p "preset=slower" -p"tune=film" -p"size=1920:1080" -p"rate=30"`, but it still looks really low quality.

I would appreciate if you could give some pointers on how to achieve a better quality

**Comment by soreau** [comment]
Most codecs use YUV420 format which is a lossy compression format. Try `--codec libx264rgb` to store all of the image data.

**Comment by rhysperry111** [comment]
I should have noticed that... darn. Sorry for bugtracker spam!
