### ISSUE TITLE
build fails with "meson_options.txt:2:0: ERROR: Unknown type feature."

### ISSUE THREAD

**Issue by student4k** [ammen99/wf-recorder#123]
OS: Ubuntu 18.04
Git commit: 2bb52d8554e66afc614c1288a6268645de6ac490 (master at 11:50 UTC 14.11.2020)

Building commands and output:
___________BUILD-OUTPUT-BEGIN____________________________________________________________
$ sudo apt install libavutil-dev libavcodec-dev libavformat-dev libswscale-dev libpulse-dev
$ git clone https://github.com/ammen99/wf-recorder.git && cd wf-recorder
...
$ meson build --prefix=/usr --buildtype=release
The Meson build system

Version: 0.45.1
Source dir: /home/u1/dist/wf-recorder
Build dir: /home/u1/dist/wf-recorder/build
Build type: native build

meson_options.txt:2:0: ERROR: Unknown type feature.

A full log can be found at /home/u1/dist/wf-recorder/build/meson-logs/meson-log.txt
___________BUILD-OUTPUT-END____________________________________________________________

meson-log.txt attached.

[meson-log.txt](https://github.com/ammen99/wf-recorder/files/5540630/meson-log.txt)

**Comment by ammen99** [comment]
Your meson is probably outdated, can you try updating it?

**Comment by student4k** [comment]
Have tried on Ubuntu 20.04. The building goes further, but still fails:

_______________BUILD-OUTPUT-BEGIN__________________
[u1@l2 wf-recorder (master)]$ meson build --prefix=/usr --buildtype=release
The Meson build system
Version: 0.53.2
Source dir: /home/u1/sandbox/wf-recorder
Build dir: /home/u1/sandbox/wf-recorder/build
Build type: native build
Project name: wf-recorder
Project version: 0.2.1
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
C++ compiler for the host machine: c++ (gcc 9.3.0 "c++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C++ linker for the host machine: c++ ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Found CMake: /usr/bin/cmake (3.16.3)
Run-time dependency wayland-client found: NO (tried pkgconfig and cmake)

meson.build:26:0: ERROR: Dependency "wayland-client" not found, tried pkgconfig and cmake

A full log can be found at /home/u1/sandbox/wf-recorder/build/meson-logs/meson-log.txt
_______________BUILD-OUTPUT-END__________________

Full log attached.
[meson-log.txt](https://github.com/ammen99/wf-recorder/files/5542134/meson-log.txt)

**Comment by ammen99** [comment]
The error message tells you what it needs, install wayland-client-dev or wayland-dev or whatever the name is :)
