### ISSUE TITLE
FR: Record current output

### ISSUE THREAD

**Issue by varac** [ammen99/wf-recorder#124]
It would be nice if you could start wf-reorder with sth like `--output current` or `--output focussed` and it would capture the output where wf-recorder is started from.

**Comment by ammen99** [comment]
This is pretty much impossible,  we can't know which output the compositor has focused (at least in wayland) - and we have even less information on which output wf-recorder was started.

I would suggest that you somehow get the focused output from Sway's IPC or similar, and then create a wrapper for wf-recorder which does that.

**Comment by varac** [comment]
> This is pretty much impossible, we can't know which output the compositor has focused (at least in wayland) - and we have even less information on which output wf-recorder was started.
> I would suggest that you somehow get the focused output from Sway's IPC or similar, and then create a wrapper for wf-recorder which does that.

I don't understand - when I get the currently focussed output from my existing wrapper script with

    swaymsg -t get_outputs| jq -r '.[] | select(.focused ).name'

why can't wf-recorder do that in a similar simple fashion ? The reason I'm asking to include this in wf-recorder is that I'd like to use it without further intervention from different scripts and it makes more sense to me to bake this logic into wf-recorder itself rather than to duplicate it in different wrappers.

**Comment by ammen99** [comment]
> why can't wf-recorder do that in a similar simple fashion ? The reason I'm asking to include this in wf-recorder is that I'd like to use it without further intervention from different scripts and it makes more sense to me to bake this logic into wf-recorder itself rather than to duplicate it in different wrappers.

The reason is that this command is Sway-specific, whereas wf-recorder is designed to be usable on many other compositors.

**Comment by varac** [comment]
Oh right, that makes sense. thx anyway for wl-recorder !

**Comment by apiraino** [comment]
leaving here the (ugly) solution I've found:
```
#!/bin/bash
output_name=$(swaymsg -t get_outputs | jq -r '.[] | select(.focused ).name')
output_id=$(
    false | wf-recorder 2>&1 | grep $output_name | cut -d"." -f 1
)
echo -n $output_id | wf-recorder -f ~/tmp/recording.mp4
```
