### ISSUE TITLE
Can't get wf-recorder to use the correct audio device

### ISSUE THREAD

**Issue by Hubro** [ammen99/wf-recorder#129]
If I run "wf-recorder -a" with no argument, it records my microphone, not my audio output.

My audio output device looks like this in `pactl list sinks`:

```
Sink #2
	State: SUSPENDED
	Name: alsa_output.pci-0000_11_00.4.analog-stereo
	Description: Starship/Matisse HD Audio Controller Analog Stereo
```

I have tried:

- `wf-recorder --audio=2`
- `wf-recorder --audio=alsa_output.pci-0000_11_00.4.analog-stereo`
- `wf-recorder --audio="Starship/Matisse HD Audio Controller Analog Stereo"`

In all cases I get no audio:

```
Using PulseAudio device: Starship/Matisse HD Audio Controller Analog Stereo
Failed to connect to PulseAudio: Invalid argument
Recording won't have audio
```

What am I doing wrong?

---

```
~ 
❯ cat /etc/*-release           
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux

~ 
❯ pacman -Q | grep wf-recorder
wf-recorder 0.2.1-1
```

**Comment by soreau** [comment]
As [the wiki](https://github.com/ammen99/wf-recorder/wiki#audio) states, you should use `pactl list sources | grep Name` to find the name to pass to the audio argument. You probably want `alsa_output.pci-0000_11_00.4.analog-stereo.monitor`

**Comment by ammen99** [comment]
Also IIRC you might need `""` around the name, depending on how your shell parses strings.

**Comment by Hubro** [comment]
> As [the wiki](https://github.com/ammen99/wf-recorder/wiki#audio) states, you should use `pactl list sources | grep Name` to find the name to pass to the audio argument. You probably want `alsa_output.pci-0000_11_00.4.analog-stereo.monitor`

Wait, that's weird. The wf-recorder man page says to run `pactl list sinks | grep Name`, which is what I did:

```
 pactl list sinks | grep Name
	Name: alsa_output.pci-0000_08_00.1.hdmi-stereo-extra4
	Name: alsa_output.usb-SteelSeries_SteelSeries_Siberia_840-00.analog-stereo
	Name: alsa_output.pci-0000_11_00.4.analog-stereo
```

That made me assume that wf-recorder could record audio from sinks, which I guess it can't. No wonder I couldn't get it to work.

```
       -a, --audio [DEVICE]
           Starts recording the screen with audio.

           [DEVICE] argument is optional.  In case you want to specify the PulseAu‐
           dio device which will capture the audio, you can run this command with
           the name of that device.  You can find your device by running pactl list
           sinks | grep Name
```

I have now read the Wiki, and it contains a lot more useful information than the man page. It's a bummer that wf-recorder can't capture from more than one source at a time. I would think recording Desktop audio and a microphone would be a very common scenario. Is there a feature request open for that?

**Comment by ammen99** [comment]
You can set up pulseaudio to have a virtual device which combines the audio, so no need to change anything in wf-recorder: https://github.com/ammen99/wf-recorder/wiki#recording-both-mic-input-and-application-sounds

**Comment by Hubro** [comment]
> You can set up pulseaudio to have a virtual device which combines the audio, so no need to change anything in wf-recorder: https://github.com/ammen99/wf-recorder/wiki#recording-both-mic-input-and-application-sounds

Well yes I saw that, but that seems to me like a tedious workaround for something that should probably be handled by the application, as that would be a dramatically better user experience. There's no need to set up PA loopback devices in OBS, for example.

In any case, my question is answered so I'll close this topic. The man pages could probably do with an update :)

Thanks for making excellent software!
