### ISSUE TITLE
How to record audio both with inner and microphone?

### ISSUE THREAD

**Issue by Me7426** [ammen99/wf-recorder#131]
I tried `wf-recorder --audio="A" --audio="B"` and it not work.

**Comment by ammen99** [comment]
The wiki explains it, you need to create a virtual pulseaudio sink and record from it: https://github.com/ammen99/wf-recorder/wiki#recording-both-mic-input-and-application-sounds

**Comment by Me7426** [comment]
Oh, I'm sorry for my negligence.

**Comment by ammen99** [comment]
No worries ;)
