### ISSUE TITLE
Scope of project from command line tool to ffmpeg input device

### ISSUE THREAD

**Issue by truesilver92** [ammen99/wf-recorder#139]
I think that this project should be changed into 2 separate projects.

1. An input device for ffmpeg https://ffmpeg.org/ffmpeg-devices.html#Description that can easily be used with existing ffmpeg techniques/filters/etc
2. A convenient ffmpeg wrapper that uses the above project under the hood

Honestly the project as is makes for a simple run it and it works, but if you try to do anything with the input, change the codec settings, do ffmpeg filters, etc. it looks much less usable. I really only need the top project. 

Are the problems I am listing valid? Or am I just misunderstanding how to use the `-p` command to pass the other ffmpeg options?

**Comment by soreau** [comment]
You might have a look at #38

**Comment by truesilver92** [comment]
> You might have a look at #38

It looks like a similar request/implementation as #77 where someone is trying to expand the features of wf-recorder to include a few more of the features that ffmpeg has. I think it is the wrong direction to take in making a screen recorder that works in wayland

**Comment by truesilver92** [comment]
> I do not think what you suggest is the intentions of this project. You are free to fork the project and make your own changes.

I agree that I can put in the work if that is what I want changed.

@soreau What do you think the intention of this project is? It looks to me like the point is to very slowly feature creep into feature parity with ffmpeg.

The reason I am saying this in an issue here is that I wanted to see if anyone using or working on this project agrees with me, and is unaware of the input device system that ffmpeg has. It really looks like this core useful feature this project provides fits nicely along with x11grab https://ffmpeg.org/ffmpeg-devices.html#x11grab

If no one with the knowledge of `wlr-screencopy-v1`, etc. here is interested I'll probably try talking with libavdevice/ffmpeg devs and/or do it myself

**Comment by ammen99** [comment]
Does ffmpeg allow external input devices at all (i.e not built-in in ffmpeg)? Is there a simple example of how to do that?

**Comment by truesilver92** [comment]
Sadly it looks like ffmpeg does not have a plugin system for the input devices, we may need to ask the ffmpeg-devel mailing list. Looking at https://git.videolan.org/git/ffmpeg.git in the `libavdevice` folder you can see all the input and output device definitions. I think these probably show the examples on how to do it

**Comment by ammen99** [comment]
Looking at this again, I don't imagine myself doing this. If someone does it, I guess we'll have a project which will supersede wf-recorder entirely.
