### ISSUE TITLE
non-interactive capture to the /dev/video

### ISSUE THREAD

**Issue by denisok** [ammen99/wf-recorder#140]
with #115 implemented I can't bind ```wf-recorder -g "$(slurp)" --muxer=v4l2 --codec=rawvideo --file=/dev/video0 --pixel-format yuyv422``` to the hot key as /dev/video0 alway exist, and it requires confirmation.

Could we have a force option or maybe check in `stat` if that a special file/device?

**Comment by soreau** [comment]
Yes, a patch could be accepted to do what you are suggesting. In the meantime you can use something like `wf-recorder ... -f /dev/video0 <<< y`
