### ISSUE TITLE
Make --audio record output audio?

### ISSUE THREAD

**Issue by PowerMan2206** [ammen99/wf-recorder#143]
As it is, the `-a` flag records my microphone's audio. I'd like it to record the actual output audio (like if I was playing a video/music/game, so that the audio of that can be heard). Is this possible with wf-recorder or do I have to create a kind of virtual mic that takes the output audio?

**Comment by ammen99** [comment]
From the man page:

```
     -a, --audio [DEVICE]
             Starts recording the screen with audio.

             DEVICE argument is optional.  In case you want to specify the PulseAudio device which will capture the
             audio, you can run this command with the name of that device.  You can find your device by running
                   $ pactl list sinks | grep Name
```

Pulseaudio automatically creates the 'virtual mic' so you just need to figure out the correct name :)

Closing, but feel free to ask more questions here if you need further assistance.

**Comment by PowerMan2206** [comment]
That's the thing, I tried every line from `pactl list sinks | grep Name`, but none of them work. Always takes the mic input.

**Comment by PowerMan2206** [comment]
Update: it works, but I have to plug out my audio interface, otherwise it always picks up the mic. Weird

**Comment by petabyteboy** [comment]
I'm having the same issue, can we reopen?

**Comment by ammen99** [comment]
> I'm having the same issue, can we reopen?

Can you post the exact command you are using?

**Comment by petabyteboy** [comment]
```
[pbb@amalthea:~]$ pactl list sinks | grep Name
	Name: alsa_output.pci-0000_00_1b.0.analog-stereo
	Name: echoCancel_sink

[pbb@amalthea:~]$ pactl list sources | grep Name
	Name: alsa_output.pci-0000_00_1b.0.analog-stereo.monitor
	Name: alsa_input.pci-0000_00_1b.0.analog-stereo
	Name: echoCancel_source
	Name: echoCancel_sink.monitor

[pbb@amalthea:~]$
```

I tried alsa_output.pci-0000_00_1b.0.analog-stereo, echoCancel_sink and echoCancel_sink.monitor. All of those resulted with the microphone being recorded.

**Comment by ammen99** [comment]
Does this work:

```
wf-recorder -a"alsa_output.pci-0000_00_1b.0.analog-stereo.monitor"
```

?

**Comment by petabyteboy** [comment]
Ah, yes! Maybe the documentation should mention that one should add ".monitor", or use `pactl list sources | grep Name` instead of `pactl list sinks | grep Name`.

**Comment by ammen99** [comment]
You're right, the manpage is outdated ... Fixed it in https://github.com/ammen99/wf-recorder/commit/2a901365571de8b86a7eaf95fe9d0cd5a5645579
