### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ainola** [ammen99/wf-recorder#145]
Thanks for your wonderful work on this software!

https://github.com/ammen99/wf-recorder/commit/0b74ad4ec264e648ab91949aa182c5c22aa09885 contains a handy UX improvement that can prevent some data loss. I myself just overwrote a great recording accidentally T.T.

It'd be great to get a release so others don't suffer the same fate :(

**Comment by ojab** [comment]
And https://github.com/ammen99/wf-recorder/pull/56 is also handy, right now `wf-recorder  -g "$(slurp)"`  with `1.5` scale results im `[libx264 @ 0x7f2558002440] height not divisible by 2 (996x1563)` error most of the time.
