### ISSUE TITLE
[Feature Request] Add a command line option to stop recording after X amount of time.

### ISSUE THREAD

**Issue by i-right-i** [ammen99/wf-recorder#156]
[Feature Request] Add a command line option to stop recording after X amount of time.

**Comment by ammen99** [comment]
> [Feature Request] Add a command line option to stop recording after X amount of time.

What is the problem with `sleep N && pkill -INT wf-recorder` ?

**Comment by i-right-i** [comment]
Absolutely nothing, that works very nice thank you. I didn't realize there was a -INT kill signal. And thanks again for you work on wf-recorder!
