### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by bhepple** [ammen99/wf-recorder#159]
It's been a while ... 41 changes sine 0.2.1 ... or should packages release against the current state of 'origin/master'

**Comment by ammen99** [comment]
I was hoping to get #133 merged before a `0.3.0` release.

**Comment by bhepple** [comment]
Sounds good!

**Comment by ainola** [comment]
Hi, @ammen99! Now that it's been merged do you think wf-recorder is ready for another release? I ask because ffmpeg 5.0.0 is getting prepared in Arch Linux and while the latest commit builds fine with it, 0.2.1 does not.

**Comment by ammen99** [comment]
https://github.com/ammen99/wf-recorder/releases/tag/v0.3.0
