### ISSUE TITLE
Widget for waybar

### ISSUE THREAD

**Issue by timsofteng** [ammen99/wf-recorder#160]
Hello. I have idea about wf-recorder widget in waybar.
Is it possible to implement stopwatch with rec icon for waybar when wf-recorder start to work? And disable it when it finish.

**Comment by ammen99** [comment]
That would be something to implement in waybar , not wf-recorder, open an issue there. Should be easily doable, on click waybar starts wf-recorder, on stop it sends SIGINT to wf-recorder.

**Comment by yschaeff** [comment]
I have this. Plus some CSS to make it look nice. 

`    "custom/recording": {
        "format": "[{}]",
        "exec": "pidof wf-recorder > /dev/null && echo 'REC'",
        "interval": 10,
    },
`

**Comment by yschaeff** [comment]
> Is it only one way to do it to trigger pidof every time?

No, you can instead write a script that will loop and write a line on
every change. Or use signal option of waybar.

Than either wrap your call to wf-recorder to something that writes a
pidfile for which you can `inotify-wait` or sends a signal directly to
waybar with `kill`. (tip: use trap in your shell script)
