### ISSUE TITLE
Sending to OBS

### ISSUE THREAD

**Issue by 3lpsy** [ammen99/wf-recorder#17]
Is there any way to send the output of wf-recorder to OBS?

**Comment by emersion** [comment]
Related: https://hg.sr.ht/~scoopta/wlrobs

**Comment by ammen99** [comment]
wf-recorder outputs to a file via ffmpeg. Can OBS pick up input from a file?

**Comment by 3lpsy** [comment]
Thanks @emersion. Unfortunately, I tried that extension but it didn't seemed to be working so I was hoping to hack something together with just wf-recorder (if it was supported / been done before). I'll follow up with wlrobs to see if I can get that extension working. Thanks again and appreciate your work.

**Comment by emersion** [comment]
I don't think reading from a file that's being written to is going to work.

@3lpsy, please report bugs to the developer :)

**Comment by ammen99** [comment]
@emersion You're probably right, OBS should use a custom backend like the one you linked.
