### ISSUE TITLE
Is it possible to pipe wf-recorder output to an RTMP stream?

### ISSUE THREAD

**Issue by acoolstraw** [ammen99/wf-recorder#172]
I saw some issues about streaming, is it possible to pipe the output of `wf-recorder` to an RTMP server?

**Comment by ammen99** [comment]
It should be possible, just specify the rtmp server url as the output file. You may also need to specify the muxer manually (`-m`) option, iirc I needed `-m flv` to stream to twitch before.

Closing, but feel free to ask if you have more questions on the topic.

**Comment by ammen99** [comment]
Just tried setting up a twitch stream, it was as easy as `wf-recorder -f rtmp://live-prg.twitch.tv/app/live_X_Y`, I didn't need to specify anything else, so it seems like ffmpeg's autodetection magic has gotten even better in the last few years.
