### ISSUE TITLE
Overwrite existing recording without asking

### ISSUE THREAD

**Issue by apiraino** [ammen99/wf-recorder#174]
Hi, I've upgraded to wf-recorder 0.3.0 and now I can't overwrite anymore an existing recording.

I understand the use case of #115 but I have the opposite need :) In addition since I use Sway and often have two monitors attached I [script wf-recorder as follows](https://github.com/ammen99/wf-recorder/issues/124#issuecomment-1110321983):
```
# On multi-monitor setup, retrieve the one with focus (ex. "DP-1")
output_name=$(swaymsg -t get_outputs | jq -r '.[] | select(.focused ).name')
output_id=$(
    false | wf-recorder 2>&1 | grep $output_name | cut -d"." -f 1
)
echo -n $output_id | wf-recorder -f ~/tmp/out.mp4
```

Now I can't do this anymore. Is there a way to also add a `yes` somewhere to skip the overwrite prompt? Or an additional patch to add a `--force` parameter would be needed?

As a workaround I can record to ``~/tmp/`date +%Y%m%d-%H%M%S`-out.mp4`` ...

Thanks for wf-recorder!

**Comment by ammen99** [comment]
Try something like `printf "Y\n$output_id\n" | wf-recorder -f ~/tmp/out.mp4`

**Comment by ammen99** [comment]
I guess you'd also want to not print Y if the file would not be overwritten, huh. It might be a good idea to add an option for this

**Comment by apiraino** [comment]
I think I can live with removing the file prior to running wf-recording but if you prefer I can submit a patch to add a an additional parameter (`-O --overwrite-output`) for evaluation (no pressure to merge)

**Comment by soreau** [comment]
Does `wf-recorder -f ~/tmp/out.mp4 <<< Y` work?

**Comment by apiraino** [comment]
> Does `wf-recorder -f ~/tmp/out.mp4 <<< Y` work?

that was a nice trick, but `echo -n $output_id | wf-recorder -f ~/tmp/out.mp4 <<<Y` seems it's not working

**Comment by soreau** [comment]
How about `printf '%s\n' Y $output_id | wf-recorder -f ~/tmp/out.mp4`?

**Comment by soreau** [comment]
Actually, `wf-recorder -o $output_name -f ~/tmp/out.mp4 <<< Y`, which eliminates the need to translate output to numeric representation, if I understand correctly what you are doing.

**Comment by apiraino** [comment]
@soreau Can't believe I've overlooked that param for so long :facepalm: 

The correct solutions are:
```
# record a portion of the screen, no output id is needed
wf-recorder -g "$(slurp)" -f out.mp4 <<<Y

# record full screen from a specific output (i.e. which display to capture from)
printf "Y\n" | wf-recorder -o DP-1 -f out.mp4
```

apologies for stealing time for this and thanks for your support :)

**Comment by soreau** [comment]
> apologies for stealing time for this and thanks for your support :)

No problem, glad it works for you :+1:
