### ISSUE TITLE
GPU encoding error

### ISSUE THREAD

**Issue by mooreye** [ammen99/wf-recorder#186]
Manpage says:

```
To use GPU encoding, use a VAAPI codec (for ex.  ‘h264_vaapi’ ) and specify a GPU device to use with the -d op‐
     tion:
           $ wf-recorder -f test-vaapi.mkv -c h264_vaapi -d /dev/dri/renderD128
```

However it fails with:

```
selected region 0,0 0x0
[AVHWDeviceContext @ 0x7fd5cc005c00] libva: /usr/lib64/dri/i965_drv_video.so init failed
[AVHWDeviceContext @ 0x7fd5cc005c00] Failed to initialise VAAPI connection: -1 (unknown libva error).
Failed to create hw encoding device /dev/dri/renderD128:
```

OS: Fedora 36
WM: sway 1.7
wf-recorder 0.3.0
Package `libva-intel-driver` installed (I have integrated intel GPU).

**Comment by soreau** [comment]
You might check `vainfo` to see if your va drivers are working at all.

**Comment by mooreye** [comment]
> You might check `vainfo` to see if your va drivers are working at all.

Your right, they don't work:

```
$ sudo vainfo 
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva error: /usr/lib64/dri/i965_drv_video.so init failed
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```

what can I do to fix it?

**Comment by mooreye** [comment]
I needed to also install `intel-media-driver` package, now it works. Sorry.

**Comment by andradei** [comment]
> I needed to also install `intel-media-driver` package, now it works. Sorry.

Solved it for me on Arch as well. Thanks.
`vainfo` is available in the `libva-utils` package. It helps detect errors and will show a lot of details after `intel-media-driver` is installed.
