### ISSUE TITLE
Cannot send videos recordered with wf-recorder through FB Messenger

### ISSUE THREAD

**Issue by cpouldev** [ammen99/wf-recorder#189]
Hi, thanks for the app!

As the title says, I can't send any videos through FB Messenger (browser & android). Tried already on 2 different machines.

Strangely, the only videos I can send are the very short ones (eg 2-6 sec). For larger ones, facebook's dev console threw 500 http error on upload.php network call. You can (maybe?) replicate it by trying to send a 30s or 1m video via browser.

Screencasts from a Gnome session using its native recorder can be uploaded without any issues.

The command I use is this one

`wf-recorder -g "$(slurp)" -t  -f ~/Videos/screen_$(date +%Y-%m-%d_%H-%M-%S).mp4`

--

I checked past issues (https://github.com/ammen99/wf-recorder/issues/152) and the only thing that comes into my mind is the graceful termination of wf-recorder. Tried already the relevant PR but the issue still exists.

This is the only thing that keeps me back from using Sway as daily driver, any help will be deeply appreciated!

**Comment by stefonarch** [comment]
Not sure if related, but kdenlive refuses to load recording.mp4 created by wf-recorder:
![screen_window_dom_12:17:41_](https://user-images.githubusercontent.com/10681413/194751215-21dbb6a4-8243-4154-92e0-83fa81ff7cc0.png)

**Comment by ammen99** [comment]
If it is about variable refresh rate, try `--no-damage`: https://github.com/ammen99/wf-recorder/blob/master/manpage/wf-recorder.1#L85

**Comment by stefonarch** [comment]
For kdenlive this makes no diff, same message.

**Comment by cpouldev** [comment]
same for the browser. Can't play the video on android either. Here is a sample video file

https://user-images.githubusercontent.com/8311776/194762995-7b5c0198-7a1c-4e8b-911a-9e2e00a867da.mp4

**Comment by soreau** [comment]
Perhaps this is the same as #175 and the -t option will help?

**Comment by cpouldev** [comment]
I have the -t option already

**Comment by Quackdoc** [comment]
@cpouldev if you can, try to build the #190 and see if it fixes your issues, I would recommend specifying -r 30/60 or whatever your desired framerate is.

**Comment by cpouldev** [comment]
@Quackdoc thanks for your recommendation. I just built it and tried it but unfortunately the issue still persists.

If you have fb messenger, could you please try and send a full screen video (more than 40-50sec)? As I see it, the failing videos are bigger than 10MB and 30s+ long.

Or at least someone with fb messenger could try and replicate that issue

**Comment by Quackdoc** [comment]
I dont have fb meseneger, another potential issue could be the odd resolution you can try doing the below command and testing it (if you use my build you will need to rebuild it since I had a woops in the filter syntax)

the below commands should force it to record to a very "generic" output video

`--codec=libx264 -p preset=veryfast -D -r 30 -F scale=1920x1080`

**Comment by llyyr** [comment]
Could you post another sample with `-t` or a build from master? As far as I can see, the only problem with your sample video is that it is yuv444p

**Comment by cpouldev** [comment]
Sorry I forgot about that issue till I tr
