### ISSUE TITLE
Output to STDOUT / clipboard

### ISSUE THREAD

**Issue by SethFalco** [ammen99/wf-recorder#191]
Would it be viable to make to output the finished video to STDOUT or directly into the clipboard?

I only use wf-recorder for shorter videos/animations that last a few seconds and record a region on my screen. And 99% of the time, I don't need the file, but rather I'd like to just paste it in a chat to send to someone else.

I can see it's easy to output to files, but I don't see a simple way to output directly to the clipboard without. :thinking: 

For example, we can make grim output to STDOUT by passing `-`, and then pipe that over to `wl-copy`, I'm hoping there could be a similar interface for wf-recorder.

**Comment by soreau** [comment]
I don't think writing the raw video contents to stdout is something wf-recorder should do. It already uses stdout for output meant to be user readable. You would probably be better off just writing to a temporary file and using `cat` if you really want the contents on stdout. If you do this directly with wf-recorder, it might get mixed with other output. Also, pasting this into chat probably won't have the desired result. In any event, you can try something like `wf-recorder -o DVI-D-1 -m ismv -f /dev/stdout <<<Y 2>/dev/null`.

**Comment by overloader7** [comment]
`wf-recorder -m h264 -f >(wl-copy) <<<Y` 
`>(wl-copy)` makes output file a temporary that is piped directly to clipboard, `<<<Y` ignores the 'file already exists' message
