### ISSUE TITLE
src/alsa.hpp & src/alsa.cpp missing from alsa-support branch

### ISSUE THREAD

**Issue by thyrc** [ammen99/wf-recorder#192]
Hi there,

I was trying to merge the commits from master up to tag: v0.3.0 into the alsa-support branch when I noticed that the alsa source files where missing. If you still have the old files lying around somewhere, could you please share / commit them?

`meson.build:83:0: ERROR: File src/alsa.cpp does not exist.`

**Comment by ammen99** [comment]
Hi, a good point, they are still lying around! Just pushed them to the branch, I hope they are useful.
