### ISSUE TITLE
Time for 0.4 release?

### ISSUE THREAD

**Issue by Doctor-love** [ammen99/wf-recorder#195]
Hi and thanks for a great tool!

Several new features have been added since the 0.3.0 release in June, such as the ability to configure framerate and audio codec. Would you consider drafting a new release?

**Comment by blurgyy** [comment]
+1 for this, there's also https://github.com/ammen99/wf-recorder/commit/e7512572ca4a35de7ac62a6b8858a77143568a71 which fixed `pix_fmt` handling, before the commit it was problematic when using v4l2loopback with `yuyv422` pixel format.  Some discussion that might be related:

* https://github.com/ammen99/wf-recorder/issues/164#issuecomment-1160654479
* https://www.reddit.com/r/wayland/comments/z0zjpn/share_my_screen_as_a_virtual_webcam/iz49ylr/?context=3

**Comment by Doctor-love** [comment]
Bump and ping @ammen99

**Comment by kojq** [comment]
We're counting on this descriptionless program, @ammen99. Are there any plans for an upcoming release? Releases have been far and few between, but there's been an uptick in users and a good number of changes since the last release.

**Comment by ammen99** [comment]
Done :)
https://github.com/ammen99/wf-recorder/releases/tag/v0.4.0
