### ISSUE TITLE
libvpx fails to run

### ISSUE THREAD

**Issue by bhepple** [ammen99/wf-recorder#196]
I'm trying to re-package wf-recorder for fedora now that fedora has separated ffmpeg and ffmpeg-free. I'm trying to find a codec that will work with both. Obviously the default libx264 is not available in ffmpeg-free and libopenx264 is not in ffmpeg. 

I've been trying libvpx-v9 but wf-recorder takes >25s to respond to SIGINT (^C) - most users would give up, they would use pkill (SIGTERM) and find a corrupt mp4 file.

libvpx fails with ffmpeg or ffmpeg-free:
```
[mp4 @ 0x7fc058000d40] Could not find tag for codec vp8 in stream #0, codec not currently supported in container
```

I guess this is the bug that I'd like to report here but also ask what your suggestion would be for a universal codec. I should probably stay away from *vaapi|qsv|v4l2m2m|amf *  as these have hardware dependencies. *jpeg|webp* are probably not useful in this context. 

I'm told that theora is outdated and av1 is slow. Any other suggestions?

**Comment by alebastr** [comment]
> I've been trying libvpx-v9 but wf-recorder takes >25s to respond to SIGINT (^C) - most users would give up, they would use pkill (SIGTERM) and find a corrupt mp4 file.

I found that `-c libvpx-vp9 -p deadline=realtime -p speed=8` helps avoiding that particular issue. Seems to be a simple change to add the default parameters.

> `[mp4 @ 0x7fc058000d40] Could not find tag for codec vp8 in stream #0, codec not currently supported in container`

The default output container wf-recorder uses is .mp4. Apparently, ffmpeg cannot embed VP8 stream into mp4 container and .webm should be used instead. But webm only supports vp8/vp9 and cannot carry other video formats :(

So... `-c` should also select a file extension when necessary? That doesn't look as simple to implement :(

And then there's another warning,
```
[mp4 @ 0x7f1b64000f00] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 518375 >= 490161
```
which seems harmless, but should be fixed somewhere in wf-recorder.

**Comment by bhepple** [comment]
It would also help if wf-recorder printed out something on SIGINT like "wf-recorder: please wait while indexes are built"

**Comment by bhepple** [comment]
@alebastr - adding `-c libvpx --muxer webm` is a win for vp8, but the default file is recording.mp4 which may be confusing.

**Comment by Conan-Kudo** [comment]
> The default output container wf-recorder uses is .mp4. Apparently, ffmpeg cannot embed VP8 stream into mp4 container and .webm should be used instead. But webm only supports vp8/vp9 and cannot carry other video formats :(

You can use mkv for all types. webm is a subset of mkv.
