### ISSUE TITLE
Specifying a video codec

### ISSUE THREAD

**Issue by hedgepigdaniel** [ammen99/wf-recorder#2]
Thanks for making this btw :)

It would be great if it was possible to choose the ffmpeg codec. The reason I want that is that I have an intel GPU and I'd like to record the screen with low/negligible extra CPU usage by using the GPU's video encoding ability. This is possible with ffmpeg: https://trac.ffmpeg.org/wiki/Hardware/QuickSync

**Comment by ammen99** [comment]
Is changing the encoder enough? For example if you set it manually here:
https://github.com/ammen99/wf-recorder/blob/master/src/frame-writer.cpp#L48

**Comment by hedgepigdaniel** [comment]
I remember when using https://github.com/atomnuker/wlstream that changing the video codec usually resulted in having to change other options like pixel formats and the like. But essentially yes, replacing `libx264` with `h264_qsv` should make it work.

Potentially I'll try changing the hard coded values and see if I can find a set of options that works.

**Comment by foxcpp** [comment]
It would be much more user-friendly to be able to set codec options from command line.

**Comment by ammen99** [comment]
@foxcpp I am not very knowledgeable about ffmpeg, but if somebody could point me what codecs/options we need, I will gladly add support for command line arguments.

**Comment by foxpy** [comment]
> but if somebody could point me what codecs/options we need

We **totally need** `libx264` as the most portable option which provides good balance of performance, quality and file size. It's included already, fine! (though it would be nice to let user change crf and preset values).
We _may need_ `libx265` for people with multi-core horsepower (like high end Intel Core or Ryzen CPU) to fit more image quality into smaller file size. Also good thing that `libx265` has the same interface options like `libx264`.
We _may need_ `libvpx` (both VP8 and VP9) as free and open source alternative to closed H.264/H.265 format.

These were the software codecs which work everywhere. Now the GPU part...
The worst thing about GPU encoding is that it's not going to perform fine on every system there is. Also, API is going to be different for every platform.
ffmpeg supports VAAPI, VDPAU and NVENC, which are going to be suffient for screen recording in Wayland. VAAPI for Intel/AMD GPUs, VDPAU for NVIDIA/AMD GPUs and NVENC exclusively for NVIDIA GPUs.
Also I'm not even sure if VAAPI/VDPAU work in Wayland...

**Comment by hedgepigdaniel** [comment]
The ffmpeg CLI works with VAAPI and NVENC just fine in wayland. It looks like VAAPI is also usable with AMD GPUs (https://trac.ffmpeg.org/wiki/HWAccelIntro), so between VAAPI and NVENC everything should work

**Comment by ammen99** [comment]
Closing this one, the user can specify codec. The remaining work is #8

**Comment by foxpy** [comment]
Yeah, the user can specify codec, but, unfortunately, user is unable to specify codec options like crf, preset and tune. The remaining work is #9 also.
