### ISSUE TITLE
set recording frame rate

### ISSUE THREAD

**Issue by ThePiGrepper** [ammen99/wf-recorder#20]
It would be nice to be able to set the recording frame rate. In my particular use case, my system is too slow to handle a 60fps recording without seriously slowing down everything else. Is there an easy way to add this? or even hardcode it?

**Comment by ammen99** [comment]
In fact, you can easily "hardcode" it by adding a

```
usleep(17000)
```

in `main.cpp`, line 694 (so, right after the `zwlr_screencopy_frame_v1_destroy(frame);` line)


This will effectively mean that `wf-recorder` will request frames from the compositor by skipping every second one. The reason why it isn't added is that I am not sure that this is the best way to solve the problem, and may require more work in `wlroots` or in the compositor.

**Comment by ammen99** [comment]
Actually after some discussions this is indeed the way to throttle frames. But I'll have to see how to exactly figure out how much to sleep, because hardcoding it like that means that we may drop below 30fps.

**Comment by schauveau** [comment]
Another way is to receive all frames (so no sleep) and to skip the call to frame_writer->add_frame(...) according to the received frame number. I did a quick implementation that encodes at 1/n of the screen refresh rate (with n an integer specified on the command line) and so far that seems to work fine.

**Comment by norcalli** [comment]
It seems like it would be better to have the ability to use complex filters and forward flags to ffmpeg so that we can set all these options ourselves.

**Comment by schauveau** [comment]
If you are interested by ffmpeg filters, then you may want to have a look at https://github.com/ammen99/wf-recorder/issues/38 .

**Comment by norcalli** [comment]
@schauveau I am indeed. I'm interested in streaming to twitch, which I can do by just replaying the file that I record to udp with a separate ffmpeg process, though, but it might be good to have that built into wf-recorder

**Comment by soreau** [comment]
@norcalli Have you looked into https://obsproject.com/forum/resources/wlrobs.774/ ? I haven't, but it claims to be able to capture from wlroots compositors.

**Comment by norcalli** [comment]
@soreau I was hoping to avoid installing OBS (I also don't want to get too off-topic on here)
