### ISSUE TITLE
What does the "f" in wf-recorder stand for? :D

### ISSUE THREAD

**Issue by Tormen** [ammen99/wf-recorder#21]

**Comment by Tormen** [comment]
... maybe wlroots + ffmpeg recorder ... ?

Maybe that's worth mentioning in the README ?

**Comment by ammen99** [comment]
It comes from the bigger project that I am developing, Wayfire: https://github.com/WayfireWM/wayfire

So this is "Wayfire recorder". But since it uses protocols common across the wlroots compositors, it works on most of them.
