### ISSUE TITLE
Recording both desktop and webcam streams?

### ISSUE THREAD

**Issue by apiraino** [ammen99/wf-recorder#213]
I'd like to investigate if `wf-recorder` can be scripted to record multiple video input streams: namely not only the desktop (as per default) but also the video stream from the webcam (use case: record offline tutorials). I can already record from the desktop, plus microphone + desktop audio, so it's 1 video stream and 2 audio streams.

I looked at the wiki but didn't get a sense if this is doable. I'm sure there is a `ffmpeg` incantation for that, but how to translate that into a working `wf-recorder` one-liner? Working also on Wayland.

Happy to receive suggestions!

**Comment by soreau** [comment]
You can have the webcam in a window on the desktop if that works for you. See [the wiki](https://github.com/ammen99/wf-recorder/wiki#native-webcam) for a gstreamer command for it.

**Comment by apiraino** [comment]
ah! Now I connect the dots, I didnt figure that out at first :)

Works great, thanks!
