### ISSUE TITLE
Output recording plays locally but not in Firefox

### ISSUE THREAD

**Issue by buttke** [ammen99/wf-recorder#218]
Hi, when I produce a recording with `wf-recorder`, the video plays just fine locally with `mpv`. When I upload that video to, say, Discord, and try to play it in the browser, a preview appears with the correct length and a thumbnail, but playing the video does not work.

https://github.com/ammen99/wf-recorder/assets/88161263/7726efc1-7366-4112-b44a-aa6f55f27389

**Comment by buttke** [comment]
This issue occurs in Firefox but not Chromium.

**Comment by buttke** [comment]
duplicate of #152 

The `-t` flag solves this. https://github.com/ammen99/wf-recorder/issues/152#issuecomment-1166593274

**Comment by soreau** [comment]
With latest wf-recorder 0e7b2e27, do videos work in firefox/discord/messenger work with `wf-recorder -x yuv420p`? The default is yuv444p which I think may be the core problem.

Referencing related issues #189, #175, #152 and #28.

**Comment by ItsDrike** [comment]
Hey, could you perhaps make a new release with this fix? Most distributions only ship releases, and this change was only made after the latest release (which was made Sep 5). If you have some pending changes, perhaps just cherry-pick this change and only put out a release with this single change, however it seems like a pretty big issue and it's weird that it's still not in any released version.
