### ISSUE TITLE
wf-recorder -o INVALID does not complain

### ISSUE THREAD

**Issue by Tormen** [ammen99/wf-recorder#23]
Hi,

the reason for my #22 was actually that I had tried a --help and it did not recognise it (to see the options, then I was too sloppy reading the README and then I had tried -o NONSENSE to see if it complains... but it didn't ;)

Is this a bug or a feature, that an invalid parameter to -o does not yield an error?

Tormen

**Comment by ammen99** [comment]
The reason why it didn't complain is because when there is only one output, it completely discards the `-o` option - after all, there is nothing to select from. I should probably add a warning in this case, something among the lines "Warning: ignoring -o options"

**Comment by Tormen** [comment]
Works for me.

Sidenote: As personal preference I would actually prefer the command to fail if an option I provided was not used. But in either case a small warning or error message would be nice to have :)

But in any case: Thanks! :))
