### ISSUE TITLE
cutting another release that includes the `check: false` change in `meson.build`

### ISSUE THREAD

**Issue by jony255** [ammen99/wf-recorder#230]
I was unable to submit an update to the `wf-recorder` package for Void because of `run_command(git...)`

Cutting another release would help me, and others packaging this for distros that only accept versioned releases, to update our respective packages. I could patch the build file but I figure this way would be helpful for others.

https://github.com/void-linux/void-packages/pull/45884

**Comment by ammen99** [comment]
Done ;)

**Comment by jony255** [comment]
awesome, thank you! :)
