### ISSUE TITLE
Way to start and stop recordings using keybindings

### ISSUE THREAD

**Issue by samerickson** [ammen99/wf-recorder#24]
Hi there, I am using `swaywm` and as far as I can tell the way you stop the recording is by pressing `ctrl+c` but is there a way to start and stop the recording without the requirement of having a terminal open?

**Comment by ammen99** [comment]
yes, you can just kill the process with `SIGINT` (which is exactly what ctrl-c does)

**Comment by mathroc** [comment]
here is something that works for me with sway:

```
bindsym Ctrl+Shift+Print exec wf-recorder -g "$$(~/bin/slurp)" -f ~/recording_$(date +"%Y-%m-%d_%H:%M:%S.mp4")
bindsym Ctrl+Shift+BackSpace exec killall -s SIGINT wf-recorder
```

**Comment by samerickson** [comment]
Thanks for both of your help, I have been playing around with it. @mathroc thanks for your snippet including `slurp`.

**Comment by schauveau** [comment]
The timeout command, assuming that it is installed on your system, can also be useful to record for a given amount of time (or to limit the recording time to a reasonable value). For instance, to record during 10 minute: 
`timeout -s SIGINT 10m wf-recorder `

**Comment by S1ngl3-x** [comment]
Late to the party but in case anyone else is looking a for **toggle** keybinding and uses fish scripts as I do then this works for me

` bindsym $mod+Shift+R exec --no-startup-id fish -c "pgrep -x wf-recorder > /dev/null; and pkill -SIGINT wf-recorder; or wf-recorder -g (slurp) -f ~/Videos/Recordings/screencast-(date +%Y-%m-%d_%H-%M-%S).mkv"`
