### ISSUE TITLE
[FEATURE REQUEST] Web camera capture

### ISSUE THREAD

**Issue by zeionara** [ammen99/wf-recorder#245]
Hi, is it possible to capture the web camera output in a corner of the screencast? I wanted to do this using `v4l` and `obs`, but `vaapi` doesn't work for some reason and on `cpu` it is damn slow.

**Comment by soreau** [comment]
Yes, you can have something like gst-launch display the webcam while recording. See [the wiki](https://github.com/ammen99/wf-recorder/wiki#native-webcam) for a command.

**Comment by zeionara** [comment]
> Yes, you can have something like gst-launch display the webcam while recording. See [the wiki](https://github.com/ammen99/wf-recorder/wiki#native-webcam) for a command.

Thanks! Works well enough for me
