### ISSUE TITLE
Base release

### ISSUE THREAD

**Issue by lovesegfault** [ammen99/wf-recorder#25]
I'd like to package wf-recorder for Gentoo, although that becomes easier when there is a release for me to tag against. Would it be possible for you to cut an initial release of wf-recorder since it seems to be in a functional state?

**Comment by ammen99** [comment]
Yes, I'll soon merge the gif-support branch and then tag a release.

**Comment by ammen99** [comment]
Fixed: https://github.com/ammen99/wf-recorder/releases/tag/v0.1

**Comment by lovesegfault** [comment]
Cheers!
