### ISSUE TITLE
system freeze caused by VCN encoder when importing from wayland dmabuf

### ISSUE THREAD

**Issue by killown** [ammen99/wf-recorder#252]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/9497 can you update the wiki about Setting AMD_DEBUG=noefc that works around this issue, some machines may have this system freeze

**Comment by soreau** [comment]
Thanks for the report. This is a driver bug and the wiki is user-editable. You might add a 'Workarounds' section or something to put this information.
