### ISSUE TITLE
zwlr_screencopy_frame_v1@12: error 1: invalid buffer format

### ISSUE THREAD

**Issue by AmirDahan** [ammen99/wf-recorder#253]
Trying to record using ``wf-recorder -r 30 -f test.mp4 -c h264_nvenc -g "1920,0 1920x1080"``
returns an error ``zwlr_screencopy_frame_v1@12: error 1: invalid buffer format``

This issue seems to be related https://github.com/ammen99/wf-recorder/issues/250

Log:
[wf-recorder.log](https://github.com/ammen99/wf-recorder/files/14374320/wf-recorder.log)

Distro: Arch Linux
Compositor: Hyprland
Wf-recorder version: 0.4.1-c43e8e1 (Feb 22 2024, branch 'master')

**Comment by ammen99** [comment]
Seems like a duplicate, see the other issue for a potential fix. I wanted to try and solve the dmabuf path as well before merging.

**Comment by AmirDahan** [comment]
I've tried the other branch but that did not help at all
