### ISSUE TITLE
Apparent Memory Leak

### ISSUE THREAD

**Issue by John-Paul-R** [ammen99/wf-recorder#257]
I'm back!

When recording with `wf-recorder` memory usage just keeps going up, at a fairly rapid pace. I _believe_ this is a new issue. Haven't noticed it until the most recent update, at least (though `wf-recorder` was broken for me recently, until #251's last commits).

Of note, the output file does still increase in side on disk while the recording is happening.

This issue is reproducible on my machine with:

```
wf-recorder -f /tmp/$(date +'%Y-%m-%d_%H-%M-%S.mp4') -o DP-1
```

Here is a video (recorded with `wf-recorder!) of my memory ticking up until I hit my machine's limit (3x speed):

https://github.com/ammen99/wf-recorder/assets/29154459/0bbc57a1-e0bb-48d7-b537-96df1972d016

And a snapshot shortly after killing `wf-recorder`:

![wf-recorder-memleak-afterkill](https://github.com/ammen99/wf-recorder/assets/29154459/1084834a-0aba-4b80-963f-381810c3a129)

**Comment by John-Paul-R** [comment]
here are some logs:

command
```
WAYLAND_DEBUG=1 wf-recorder -f /tmp/$(date +'%Y-%m-%d_%H-%M-%S.mp4') -o DP-1 &> /tmp/vid.log
```

logs: https://gist.github.com/John-Paul-R/f09f0904240c1cb9f24f0b6237f6d3e9

**Comment by kode54** [comment]
You are aware that /tmp/ is likely to be tmpfs, and therefore you're recording to RAM, right?

**Comment by John-Paul-R** [comment]
I was not aware of that! However I also encounter the issue when recording to other directories. e.g. 

```
wf-recorder -f ~/Videos/a-real-path.mp4 -o DP-1
```

yields similar memory graphs

**Comment by kode54** [comment]
Hmm. I'll see if I can reproduce it to help out debugging it, in case the developer can't reproduce it.

**Comment by John-Paul-R** [comment]
I restarted my PC, and suddenly can no longer reproduce the issue. I suspect I had some broken local state. Closing!
