### ISSUE TITLE
Damage Tracking

### ISSUE THREAD

**Issue by ehopperdietzel** [ammen99/wf-recorder#258]
Hello,

I'm currently implementing the `wlr-screencopy` protocol within a compositor and I've noticed that damage doesn't seem to be taken into account, (in copy_with_damage requests). For instance, if I only copy the damaged regions to the `wf-recorder` buffers (both SHM and DMA), the resulting video exhibits the typical buffer tracking error glitches. Interestingly, this issue doesn't occur if I perform a full copy, and it works fine even if I don't send the correct damaged region.

So, is damage considered? and does `wf-recorder` require the compositor to always perform a full copy to the buffers?

Thank you.

Tested version: 0.4.1

**Comment by any1** [comment]
The compositor is always required to do a full copy with `wlr-screencopy-v1`. This is addressed by `ext-screencopy-v1`: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/124

**Comment by ehopperdietzel** [comment]
Thank you!
