### ISSUE TITLE
-a<device>/--audio=<device> not working?

### ISSUE THREAD

**Issue by Rabcor** [ammen99/wf-recorder#260]
whenever I try to use -a/--audio option like so:

`--audio=easyeffects_sink`
or
`--aalsa_output.pci-0000_06_00.6.analog-stereo`

it will not work, sure the output will say `Using PulseAudio device: easyeffects_sink`, but it'll say that to whatever I type even if it is not a valid device.

It does actually record audio, just not with the device I tell it to, instead it always defaults to recording my microphone, it doesn't really matter what I type, but I'm trying to get it to record the playback sound (e.g. sink). And I just cannot seem to do it.

**Comment by soreau** [comment]
It sounds like you want the .monitor device to record. Check `pactl list sources | grep Name` and use a device name that has '.monitor' appended to the end.

**Comment by Rabcor** [comment]
> It sounds like you want the .monitor device to record. Check `pactl list sources | grep Name` and use a device name that has '.monitor' appended to the end.

Hmm yes, that works, but I didn't need to do that with ffmpeg :thinking:

**Comment by ammen99** [comment]
Maybe ffmpeg has more auto-magically-working code :)

**Comment by Rabcor** [comment]
> Maybe ffmpeg has more auto-magically-working code :)

isn't wf-recorder using ffmpeg? Shouldn't it be able to leverage features ffmpeg already has?

**Comment by Rabcor** [comment]
Ah, I understand. Well you've done a good job, even if the syntax is quite odd at times it works, i was even able to fully translate my ffmpeg screencap command to wf-recorder.
