### ISSUE TITLE
How to maximize performance on Raspberry Pi?

### ISSUE THREAD

**Issue by Botspot** [ammen99/wf-recorder#263]
I am using the Raspberry Pi 5, which should have plenty of horsepower to do a good screen recording on wayland with one 1080p screen.
I need to record a fairly CPU-intensive program, so minimizing the recording overhead is important.

Here is the command I am using:
```
wf-recorder -a -f /tmp/video.mkv -c libx264 -p preset=ultrafast
```
Now for the tricky part: I also want a low-latency video feed from a webcam, in the corner of the screen. I am doing this with a `mplayer` window on-screen, displaying the webcam, so it gets picked up in the final recording.

This setup uses 70-80% CPU, and the resulting recording is fairly laggy. I had better performance on the Pi4, which has maybe a third of the processing power, on X11, so I am open to ideas for how to achieve that here. (although on the Pi4 I was using simplescreenrecorder and 30fps)

**Comment by ammen99** [comment]
You can try offloading the encoding of the video stream (which takes a large majority of the cpu time) on the gpu if the rpi5 has it. Otherwise try different ffmpeg codecs, which ones are in use in your older rpi4 setup?

**Comment by Botspot** [comment]
On my Pi4 I used a dirty hands-off approach. I simply used a low framerate on simplescreenrecorder, which only supports x11. No fancy ffmpeg stuff there.

Here is one person's suggested ffmpeg command for `*`some`*` amount of acceleration on Pi5: https://forums.raspberrypi.com/viewtopic.php?p=2226502&hilit=h264_v4l2m2m#p2226502

Then ChatGPT suggested a fairly outlandish approach which looks intriguing if it could work.
```
mkfifo /tmp/wayland_pipe
wf-recorder -f /tmp/wayland_pipe -c rawvideo &
ffmpeg -f rawvideo -pixel_format bgra -video_size 1920x1080 -framerate 30 -i /tmp/wayland_pipe -hwaccel drm -hwaccel_output_format drm_prime -c:v h264_v4l2m2m -b:v 1M -c:a aac -b:a 128k -f matroska /tmp/output.mkv
```
This fails on the second command.
```
$ wf-recorder -f /tmp/wayland_pipe -c rawvideo
Output file "/tmp/wayland_pipe" exists. Overwrite? Y/n: 
selected region 0,0 0x0
[NULL @ 0x7f88000d30] Unable to find a suitable output format for '/tmp/wayland_pipe'
Failed to allocate output context
```

**Comment by Botspot** [comment]
This is an interesting little detail. https://forums.raspberrypi.com/viewtopic.php?p=2175937&hilit=rpi5+encode#p2175937
So maybe searching for hardware encoding is not the answer, at least for pi5.

Now my questions are:
Is there a way to reduce the framerate?
Is it possible to stream a raw video to a pipe file, as chatgpt suggested?

Also, this is wf-recorder version 0.3.0

**Comment by Botspot** [comment]
I just spent several hours fiddling with alternative ways to capture the screen. This was the most 'promising' option: https://gist.github.com/digitalsignalperson/ef81c1afdc04d49f5ae3f6f97b2d29af
It used pipewire to stream the screen to a named pipe and then encode it with ffmpeg. Unfortunately, I could never get it past 4 fps and the latency was beyond 10 seconds. All this time though, the CPU load on the Pi5 was very low, so I probably just did not know how to set the options right.

Still interested in recording with wf-recorder, but just reducing the framerate.

**Comment by soreau** [comment]
I assume you have tried `wf-recorder -c h264_vaapi -d /dev/dri/renderD128 -f out.mp4` and it does not work due to hardware or driver limitations? What is the output? You might have to install additional packages to get vaapi working, if it works at all on rpi5.

**Comment by Botspot** [comment]
Yeah I tried that.
A pi dev [says](https://forums.raspberrypi.com/viewtopic.php?p=2190863&hilit=vaapi#p2190863):

> VA-API is generally used on x86 platforms for video codec acceleration. Most ARM platforms use V4L2.

The output is:
```
selected region 0,0 0x0
[AVHWDeviceContext @ 0x7fa40040b0] Failed to initialise VAAPI connection: -1 (unknown libva error).
Failed to create hw encoding device /dev/dri/renderD128:
```

**Comment by Botspot** [comment]
I would be fine with encoding the video later, but attempts to save it raw resulted in very weird output files. FFmpeg would take 10+ minutes to encode 5 seconds of video, saying there was over 10,000 duplicated frames. The filesize was also quite unreasonably large for 5 seconds - in the 100-500 MB range from my tests. Best I can imagine is that wf-recorder was capturing thousands of frames per second, for some reason.

**Comment by soreau** [comment]
At that point, maybe just use grim to capture screenshots and assemble them with ffmpeg later.

**Comment by Botspot** [comment]
> At that point, maybe just use grim to capture screenshots and assemble them with ffmpeg later.

No, I need audio feed and preferably 30fps. Seriously, the Pi5 has impressive power. Folks on the pi forums say it can encode 1080p60 with just the cpu, so it has the power necessary for sure.
Is there a way to limit frame rate?

**Comment by soreau** [comment]
Looks like you can limit the rate with an option: https://github.com/ammen99/wf-recorder/blob/master/src/main.cpp#L819

**Comment by Botspot** [comment]
My wf-recorder version on the bookworm repos must be outdated, as it does not support a `-r` flag!

**Comment by kode54** [comment]
Use a stable distribution, expect all your software to be outdated except for backported security fixes.

**Comment by Botspot** [comment]
If there was an official Raspberry Pi OS rolling distro I would switch in a heartbeat.

**Comment by kode54** [comment]
Oh, right. Pi. Duh.

**Comment by ammen99** [comment]
@Botspot I would recommend compiling wf-recorder from source, it should not be very hard. We don't have that many dependencies. Then you can limit your framerate, or make ffmpeg downscale the output resolution (so you could scale the video before encoding, which will reduce your cpu usage even further).

**Comment by Botspot** [comment]
The compile was easy and lowering frame rate helped a lot.
