### ISSUE TITLE
Software encoder fallback in case of failed hardware encoder constraints check

### ISSUE THREAD

**Issue by phisch** [ammen99/wf-recorder#275]
When recording a small buffer, and using a hardware encoder, the encoder might fail if the buffers size doesn't fit within the hardware encoders size constraints.

On an intel iGPU:
> [Parsed_scale_vaapi_1 @ 0x7aa7d8051a00] Hardware does not support scaling to size 12x8 (constraints: width 16-16384 height 16-16384).

On a dedicated AMD GPU:
> [h264_vaapi @ 0x7fcc98003580] Hardware does not support encoding at size 32x16 (constraints: width 256-4096 height 128-2304).

Whenever this constraint check fails, wf-recorder should instead use a software encoder.

**Comment by ammen99** [comment]
Disagree, it is the user's responsibility to select the appropriate codec. I don't think it is intuitive that we disobey what the user specifies explicitly on the command line.

**Comment by phisch** [comment]
@ammen99 I believe the issue is when you use something like this:

```sh
wf-recorder -c h264_vaapi -g "$(slurp)"
```
How does the user even **know** there are constraints, and how would he know what those are? Obviously you would want hardware encoding when possible, but there doesn't seem to be a good way for a user to check the constraints themselves.

**Comment by ammen99** [comment]
You can see those in the error messages, and from there you can script your way around it. The error is being printed on stderr, is it not? :)

I understand this requires some work on the user's side but I just don't like the alternatives. wf-recoder ought to be a simple tool, doing whatever the user has specified on the cmdline and little else.

**Comment by phisch** [comment]
I don't agree with that philosophy at all, but I can only suggest what I think is right.
Anyway, thanks for your work on wf-recorder!
