### ISSUE TITLE
Video file is corrupt when uploading the video to github and websites in general

### ISSUE THREAD

**Issue by Bluey26** [ammen99/wf-recorder#276]
Hi, i usually use this program to record small videos of areas of the screen, and they usually are to report and show issues in github or to upload small snippets of videos in the internet.

I have been having the issue that the videos recorder with this utility has some kind of mal-function or wrong thing, because they are not playable in firefox (last version) and previous one, but are reproducible when downloaded.

steps to reproduce:
`
wf-recorder -g "$(slurp)" --file=some_name.mp4`

then upload the file to github or some website.

OS: `archlinux` DE: `labwc+LXQt `

`wf-recorder 0.4.1-2`

![video-corrupt](https://github.com/user-attachments/assets/f5f46e62-afa1-46fc-8f7d-f94db630f535)

**Comment by soreau** [comment]
Please try with latest wf-recorder git, using default options.

**Comment by Bluey26** [comment]
Ok, i have compiled the git branch from the aur: https://aur.archlinux.org/packages/wf-recorder-git

and uploaded a test video. The issue is not present in the `git` version, so i will close this.

I should have to test that before asking, but fortunately it is solved now.

Thank you.
