### ISSUE TITLE
Default settings not playing on Safari on iOS

### ISSUE THREAD

**Issue by markstos** [ammen99/wf-recorder#278]
Details are here:
https://forum.ghost.org/t/mp4-video-not-playing-on-safari-on-ios-works-on-desktop/50281

`wf-recorder` generated an MP4 file with a h264 "Constrained Baseline" profile. This play in Safari on iOS, but after re-encoding the file with "High" profile, it worked.

Re-encoding the files with `ffmpeg -i in.mp4 out.mp4` not only resolved the compatibility issue, but the file sizes shrank by more than half. 

I'm not sure if this default compatibility or file size is a priority or not.

**Comment by soreau** [comment]
What version of wf-recorder are you using? The latest release should produce videos that are web friendly by default.

**Comment by markstos** [comment]
That was with 0.5.0, the latest release.

**Comment by soreau** [comment]
What command and options are you using to record? You can also pass parameters to the codec with `-p`. See `--help`.

**Comment by markstos** [comment]
Only an option to select an output and write to an .mp4 file. No audio.

**Comment by soreau** [comment]
> Only an option to select an output and write to an .mp4 file. No audio.

Does it make a difference if you try `.mkv`?

**Comment by soreau** [comment]
I tried this myself and it seems when I use `-c h264_vaapi`, the output profile is automatically 'High'.

**Comment by soreau** [comment]
Another way is to use `-ppreset=superfast -pprofile:v=high -plevel:v=4.0` with libx264. However you probably want to use h264_vaapi if you can, since this saves cpu resources by offloading encoding to the gpu. Closing for now, since there are ways to use High profile with wf-recorder.
