### ISSUE TITLE
How trigger run wf-recorder in the background (possibly outside the Wayland session)? 

### ISSUE THREAD

**Issue by rolfschr** [ammen99/wf-recorder#281]
Hi,

I have a VM with Wayland. Something is happening in the GUI that I like to record. `wf-recorder` installed on the virtual machine. I'm able to send commands to that machine directly. I'd like to trigger `wf-recorder`. This yields `failed to create display: No such file or directory`, however. The same is true for `WAYLAND_DISPLAY=wayland-0; wf-recorder `. Is there any clever way I could achieve this? Basically, I'd like to record the screen without any visible interaction on the screen that shows that `wf-recorder` is started.

Thank you for your tool, anyways!

**Comment by ammen99** [comment]
This should work, just make sure that wayalnd-display is set correctly. Many compositors start from wayland-1 not wayland-0, you can check by running `echo $WAYLAND_DISPLAY` inside the VM.

Also beware the syntax, it should be `WAYLAND_DISPLAY=wayland-1 wf-recorder` without the semicolon.

**Comment by rolfschr** [comment]
Thank you for the quick response! I was able to solve the problem by providing `XDG_RUNTIME_DIR`. I had seen the error (`error: XDG_RUNTIME_DIR is invalid or not set in the environment.`) in the logs but did not realize it came from (?) `wf-recorder`. So in the end, `XDG_RUNTIME_DIR=/run/user/1000 wf-recorder &` works for me.
