### ISSUE TITLE
gif recording is eating up a lot of memory on hi dpi monitor, how to lower the size?

### ISSUE THREAD

**Issue by Seme4eg** [ammen99/wf-recorder#283]
doing same recording on same region with `-c gif` and without this param results in former being 8Mb, while latter is only 3Mb. 
Commands:
- `wf-recorder -g "$(slurp)" -c gif -f "${filepath}.gif"` <- eats 2.5 more memory than 'mp4' format, same size, same time, same screen
- `wf-recorder -g "$(slurp)" -f "${filepath}.mp4"`

**Comment by Seme4eg** [comment]
those didn't help, even with -r 14 and -B 1 it still takes twise as much as mp4 recording of same length and same size. But anyway thank you for suggestion!

**Comment by soreau** [comment]
I tested this a bit and it seems that the gif codec doesn't support compressed formats such as yuv420p. libx264 codec does, and the result is clear. If you try with `-c libx264rgb`, the video contains all of the RGB data and the file size is larger than the gif case. I tested with these commands on 1920x1080@75Hz:

```
wf-recorder -y -o DP-3 -f wf-recorder.mp4 & pid=$!; sleep 5; kill $pid
wf-recorder -y -o DP-3 -c gif -f wf-recorder.gif & pid=$!; sleep 5; kill $pid
wf-recorder -y -o DP-3 -r 5 -c gif -f wf-recorder-5fps.gif & pid=$!; sleep 5; kill $pid
wf-recorder -y -o DP-3 -c libx264rgb -f wf-recorder-rgb.mp4 & pid=$!; sleep 5; kill $pid
```

these are the resulting file sizes:

```
wf-recorder-rgb.mp4  - 15914447
wf-recorder.mp4      - 7940983
wf-recorder.gif      - 11493629
wf-recorder-5fps.gif - 5549641
```

As you can see, limiting the frame rate to 5fps helped in the gif case. The results you get might be different depending especially on the size of the recording.
