### ISSUE TITLE
issues with libavcodec on fedora

### ISSUE THREAD

**Issue by vdegenne** [ammen99/wf-recorder#284]
I recently upgraded my Fedora system to version 41, and `wf-recorded` stopped working.

I have errors like the following:

```
wf-recorder: error while loading shared libraries: libavformat.so.60: cannot open shared object file: No such file or directory
```

If I try to locate the missing shared objects, e.g.

```
ll /usr/lib64 | grep libavformat
lrwxrwxrwx. 1 root root    23 Oct  7 02:00 libavformat.so -> libavformat.so.61.1.100
lrwxrwxrwx. 1 root root    23 Oct  7 02:00 libavformat.so.61 -> libavformat.so.61.1.100
-rwxr-xr-x. 1 root root  2.6M Oct  7 02:00 libavformat.so.61.1.100
```

shows `libavformat.so.60` is outdated(?) from my system and trying

```
dnf requires libavformat.so.60
```

has no installation candidates... So I'm unable to use `wf-recorded` for now. 

Do I have to wait you guys do the update, or is the problem easily fixable from my side?

**Comment by soreau** [comment]
Does it work if you build wf-recorder yourself (from git)?

**Comment by vdegenne** [comment]
Never mind... uninstalling and installing wf-recorder again using dnf fixed it (weird).

Also for the record I tried to build sources and it works too now. Maybe it was stuck on an old version I built in the past.
