### ISSUE TITLE
Recorded video is rotated when the monitor (wl_output) is rotated

### ISSUE THREAD

**Issue by ideasman42** [ammen99/wf-recorder#289]
With vertical monitors (rotated using wlr-randr), the video file is rotated.

Ideally the rotation of the monitor would be taken into account.
Failing that, an option to manually rotate could work.

- Using the `--filter "rotate=-90*PI/180"`  argument doesn't really work unless the region is exactly square.
- It's not such a problem to rotate it with FFMPEG but annoying to have to re-encode. e.g.
  `ffmpeg -i ~/screenrecord.mp4 -vf "transpose=3"  ~/screenrecord_rotated.mp4`.

**Comment by ammen99** [comment]
Have you tried combining the two filters together?

```
wf-recorder --filter "rotate=-90*PI/180" --filter "transpose=3"
```

Seems to do the trick here.

**Comment by ideasman42** [comment]
Thanks, it turns out `--filter "transpose=2"` was all that was needed.

`wl-screenrecord.sh` example:
```bash
#!/usr/bin/env bash
wf-recorder -g "$(slurp)" --filter "transpose=2" --overwrite --file ~/screenrecord.mp4
notify-send '~/screenrecord.mp4 created!'
```

**Comment by soreau** [comment]
Thanks for sharing your solution! Closing this because I don't think automating this is planned, though PR's are welcome.
