### ISSUE TITLE
param '-P'  dont work

### ISSUE THREAD

**Issue by oblivcheck** [ammen99/wf-recorder#291]
```
wf-recorder -a -c libx264 -r 25 -x yuv444p -f test.mp4 -F scale=1280:-1  -C aac --audio-codec-param b=384k
```
```
wf-recorder -a -c libx264 -r 25 -x yuv444p -f test.mp4 -F scale=1280:-1  -C aac -P b=384k
```
AAC audio bitrate always lock to 128k

it doesn't even output like:
```
Setting codec option: .........
```

#268 
#135 
#79

**Comment by soreau** [comment]
Does it work if you try `-Pb=384k`  or `--audio-codec-param='b=384k'`?

**Comment by oblivcheck** [comment]
> Does it work if you try `-Pb=384k` or `--audio-codec-param='b=384k'`?

not work

**Comment by soreau** [comment]
Hm, I see that `load_audio_codec_options()` is defined but never called anywhere it seems. Maybe you have found a bug.

**Comment by soreau** [comment]
Does [this patch](https://termbin.com/dev5c) help?

**Comment by oblivcheck** [comment]
same, dont work

**Comment by soreau** [comment]
Can you elaborate about what you've tried that isn't working after applying the patch? Do you still not get the message stating the option set?

**Comment by soreau** [comment]
Here, is I run `$ wf-recorder -o DP-3 -a -Pb=384k -f /tmp/wf-recorder.mp4`, I at least see the output `Setting codec option: b=384k`.

**Comment by oblivcheck** [comment]
> Do you still not get the message stating the option set?
yes

```

./wf-recorder  -a -c libx264 -r 25 -x yuv444p -f test.mp4 -F scale=1280:-1  -C aac --audio-codec-param b=384k
./wf-recorder  -a -c libx264 -r 25 -x yuv444p -f test.mp4 -F scale=1280:-1  -C aac -P b=384k
./wf-recorder  -a -c libx264 -r 25 -x yuv444p -f test.mp4 -F scale=1280:-1  -C aac -P b=192k
./wf-recorder  -a -c libx264 -r 25 -x yuv444p -f test.mp4 -F scale=1280:-1  -C aac -P b=192
./wf-recorder  -a -c libx264 -r 25 -x yuv444p -f test.mp4 -F scale=1280:-1  -C aac  -Pb=384k
./wf-recorder  -a -c libx264 -r 25 -x yuv444p -f test.mp4 -F scale=1280:-1  -C aac  --audio-codec-param='b=384k'
./wf-recorder  -a -c libx264 -r 25 -x yuv444p -f test.mp4 -F scale=1280:-1   --audio-codec-param='b=384k'
./wf-recorder  -a -c libx264 -r 25 -x yuv444p -f test.mp4 -F scale=1280:-1  -C aac  -Pb=384k
./wf-recorder  -a -c libx264 -r 25 -x yuv444p -f test.mkv  -C aac  -Pb=384k
./wf-recorder  -a -c libx264 -r 25 -x yuv444p -f test.mkv  -C aac  -P b=384k

```

**Comment by soreau** [comment]
Can you show the complete output with `-Pb=384k` set? Maybe the patch isn't applied correctly or something.

**Comment by soreau** [comment]
It's right there.. `Setting codec option: b=384k`..

**Comment by oblivcheck** [comment]
> It's right there.. `Setting codec option: b=384k`..

sorry, I didn't see

**Comment by oblivcheck** [comment]
but 
```
Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp, 128 kb/s
```

**Comment by soreau** [comment]
I think the only thing that can be done here is to decrease the audio bitrate, not increase it. This can be accomplished by setting the audio sample rate with `-R`. Here, the only way I was able to make a difference was with `-R8000` which gave `Stream #0:1: Audio: aac (LC), 8000 Hz, stereo, fltp, 96 kb/s` instead of 128k.

**Comment by soreau** [comment]
Actually, with `-Clibfdk_aac` I can ` wf-recorder -o DP-3 -Clibfdk_aac -a -R96000 -Pb=256k -f /tmp/wf-recorder.mp4` and get `Stream #0:1: Audio: aac, 96000 Hz, stereo, s16, 279 kb/s`. So I think you have found a bug in general, but it will require experimentation to do whatever it is you're trying to do.

**Comment by oblivcheck** [comment]
Honestly, I'm not sure if this is a problem with wf-recoder. 
Maybe it's impossible to adjust the bitrate without change the sampe rate?

**Comment by soreau** [comment]
You are right about `-P`/`--audio-codec-param` not doing anything, this is what the PR fixes, specifically. But so far as changing the audio bitrate, I do think it is directly related to the audio sample rate.

**Comment by meengu** [comment]
Hi, it's due to options not being passed to avcodec, despite being parsed. Fix is simple:

https://xff.cz/0001-Actually-use-parsed-audio-options-when-opening-audio.patch

**Comment by soreau** [comment]
> Hi, it's due to options not being passed to avcodec, despite being parsed. Fix is simple:
> 
> https://xff.cz/0001-Actually-use-parsed-audio-options-when-opening-audio.patch

@meengu Can you possibly make a pull request with your patch?

**Comment by meengu** [comment]
I don't think so. You'd probably have to allow me to push branches to your repository to be able to do so. I don't want to create forks on this account. I suggest you just download the patch and run git am on it if you want fix the -P param not working issue.

**Comment by soreau** [comment]
> I don't think so. You'd probably have to allow me to push branches to your repository to be able to do so. I don't want to create forks on this account. I suggest you just download the patch and run git am on it if you want fix the -P param not working issue.

`curl https://xff.cz/0001-Actually-use-parsed-audio-options-when-opening-audio.patch | git am` worked nicely. Thank you for giving permission to use your patch this way.

**Comment by meengu** [comment]
Thank you. :)
