### ISSUE TITLE
add simple gtk interface

### ISSUE THREAD

**Issue by akrram09** [ammen99/wf-recorder#293]
it would be great if you can add simple interface to it for recording, selecting area and choose if to include audio or not a lot of time i forget that i have this tool or even the name and i have to search in my terminal history it would be much simple and easy to just open the app and record

**Comment by ammen99** [comment]
wf-recorder is a command-line tool, no plans to add a GUI. It adds a lot of code to the project. I would recommend pairing this with slurp for interactive selection. You can make a keybinding and then you won't have to remember the name :)
