### ISSUE TITLE
Color accuracy when using vaapi

### ISSUE THREAD

**Issue by schauveau** [ammen99/wf-recorder#33]
What follows is not really a bug report because I already found the solution. Hopefully, the following information could be helpful to other users. 

I noticed that the colors are not accurate when using vaapi (i965 driver). Simply speaking the shadows are darker while the highlights are brighter. On my system, this is especially noticeable because all my terminals and editors are using a dark background that becomes completely black in the recording.   

I eventually figured out that vaapi is probably assuming an MPEG color range (16-235) instead of the full range (0-255) when doing the RGB to YUV conversion.
      
A possible solution is to add the -t option to do the conversion from RGB to YUV in software but this is not ideal since that can significantly increase the cpu usage. 

So a better solution that works with h264_vaapi and hevc_vaapi is to pass the codec option color_range=2. Unfortunately that does not seem to work for the other vaapi codecs.

`wf-recorder -c h264_vaapi  -d /dev/dri/renderD128 -p color_range=2`

The attached image shows from left to right, a reference image, a vaapi screencast with bad colors, and the same screencast with the option color_range=2.  

![color-range](https://user-images.githubusercontent.com/14061306/59151185-fd0b0f80-8a2e-11e9-84b6-6c41759c29fb.png)

**Comment by soreau** [comment]
There is an [opencl branch](https://github.com/soreau/wf-recorder/tree/opencl) you can try. With this branch, use -e in addition to -t to use opencl instead of software the make the conversion, which should lessen cpu usage. Hopefully this helps.

**Comment by schauveau** [comment]
Thanks. h264_vaapi + color_range=2 is currently good enough for me but I'll give opencl a try.

**Comment by ammen99** [comment]
@schauveau, `-t` increases cpu usage, but `-t -e` should use opencl for conversion so it should work too (useful for the other affected codecs)

**Comment by soreau** [comment]
I would consider this as a bug in the driver, the default shouldn't be to clip the color range for rgb input. But perhaps we could add this as a default x26x option? @ammen99 Should this go in load_codec_options()?

**Comment by schauveau** [comment]
Be careful because in my experiments, I noticed that specifying color_range=2 when the colors are already correct is inverting the effects (the shadows are too bright while the highlights are too dark), So as far as I can tell, color_range=2 must only be used for h264_vaapi and hevc_vaapi when the -t options is not used.

**Comment by soreau** [comment]
@schauveau Ok thanks. I wonder if there is a way to tell if it's using the full range or not.

**Comment by schauveau** [comment]
That may also be a problem with the i965 driver. It is probably better to document the issue and let the user decide if the option is needed.

**Comment by schauveau** [comment]
The information is probably in the FFmpeg documentation ... just kidding!

**Comment by soreau** [comment]
@schauveau You said 'when the colors are already correct'. When does this occur, with vp8 vaapi or something?

**Comment by schauveau** [comment]
I am aware of the following 'correct' cases that become incorrect when I add `-p color_range=2`:
- `wh-recorder -c h264_vaapi  -t  -d ...` 
- `wh-recorder -c hevc_vaapi  -t  -d ...` 
- `wh-recorder -c libx264` 
There are probably more.

**Comment by schauveau** [comment]
I figured out the problem while working on my filter experiment (see https://github.com/ammen99/wf-recorder/issues/38 ). The default behavior of sws_scale is to set the output color range to 'mpeg' .
You probably need to pass additional options to sws_config: 
```
in_range=jpeg
out_range=jpeg
```

**Comment by schauveau** [comment]
Crap! I was trying to cancel my comment. Not close the whole ticket :-)

**Comment by ammen99** [comment]
Closing this since the user has enough options to get correct results (might be a bit confusing, but this is thanks to ffmpeg)
