### ISSUE TITLE
"Failed to find the aac codec"

### ISSUE THREAD

**Issue by keithbowes** [ammen99/wf-recorder#34]
Maybe I'm missing something (after all, this isn't very well-documented, as noted in issue #26), but there doesn't seem to be a way to choose a free audio format unencumbered by patents like there is for video.  Sure, it took me ages to figure out how to get the video codec to work:
wf-recorder -f out.webm -c libvpx

That works fine for video, but when I try to record audio, it complains about not being able to find the aac codec.  I've tried to figure out how to specify libvorbis/opus audio with an argument to -a/--audio (wf-recorder -f out.webm -c libvpx -a libvorbis), and by specifying another -c after -a ( wf-recorder -f out.webm -c libvpx -a -c libvorbis) (the former still complains about not being able to find aac, the latter causes a segfault).

**Comment by ammen99** [comment]
Currently aac codec is hardcoded. I am not against adding an option to change it though.

Also, the `-a` option is about selecting the audio device to capture from.

**Comment by ammen99** [comment]
This is now fixed with #177
