### ISSUE TITLE
Build issue on arch

### ISSUE THREAD

**Issue by hughwilliams94** [ammen99/wf-recorder#37]
When building the AUR package, I get this issue:

```ninja: error: '../wf-recorder/manpage/wf-recorder.1.scd', needed by 'wf-recorder.1', missing and no known rule to make it```

Any idea how to fix?

**Comment by ammen99** [comment]
This one: https://github.com/ammen99/wf-recorder/pull/36

**Comment by ammen99** [comment]
Just merged #36, please reopen if this continues to happen.
