### ISSUE TITLE
Option parsing for audio device is inconsistent with spaces

### ISSUE THREAD

**Issue by norcalli** [ammen99/wf-recorder#39]
I spent quite some time chasing my tail over an assumption I made that turned out to be false.

```
wf-recorder -a 1
```

does not result in the same thing as

```
wf-recorder -a1
```

The first command uses the `default` device and ignores the argument. `--audio=1` works as expected.

**Comment by ammen99** [comment]
I am using getopt_long to parse arguments, so any strangeness comes from it.

**Comment by soreau** [comment]
From the getopt manpage:
```
A simple short option is a '-' followed by a  short  option  character. If the option has a required argument, it may be written directly after the option character or as the next parameter (i.e. separated by white‐space on the command line).  If the option has an optional argument, it must be written directly after the option character if present.
```

**Comment by ammen99** [comment]
This is simply how getopt_long works.
