### ISSUE TITLE
non-file output for streaming purposes

### ISSUE THREAD

**Issue by disruptek** [ammen99/wf-recorder#40]
I'm actually using the fork from @schauveau but I started with this branch, and he doesn't have issues enabled on his repository.  :-P

I tried to hack in support for non-file output, but it looks like one cannot mux without seeking.  I'd be satisfied with a pipe, but again, without the ability to seek...  Any tips on how to go about adding this functionality?  I'm shooting in the dark when it comes to the ffmpeg API.

/cc @norcalli

**Comment by schauveau** [comment]
Hoops! I just enabled issues on my branch.
I am do not know how to support non-file output (this is probably not possible in my branch) but there could be an easier way to handle your problem. If you do not care about audio then you could replace the complete writer by a simple piece of code that sends the raw rgb frames to a ffmpeg process through a pipe (typically using popen). The cost of using a pipe is quite small, the resulting code will a lot easier to maintain and you would have access to the full capabilities of ffmpeg.

**Comment by ammen99** [comment]
It should be possible even with the current model, the now-deprecated wlstream can do this.

**Comment by ammen99** [comment]
I just looked, it looks like only minimal changes to wf-recorder are needed to enable streaming. I'll implement it a bit later.

**Comment by schauveau** [comment]
Ha! I see. This is the part that handles the rtmp and udp prefixes in wlstream. It would be helpful to have an example of ffmpeg command showing what disruptek want to do exactly.

**Comment by schauveau** [comment]
@disruptek I added an option --file-format (or -F) in my branch.  Unless I missed something, wlstream was setting the file format to `"flv"` for rtmp streaming and `"mpegts"` for udp. I do not have any way to test if that works.

**Comment by ammen99** [comment]
@schauveau I already have a patch for wf-recorder, but I want to first test it, which can happen in a few hours (since the Wi-Fi network I'm using disallows streaming)

**Comment by disruptek** [comment]
Yes, I got it working; it was a stupid bug on my part.  I was also able to test Stephane's branch and it works with this minor patch to hint at the format a couple lines earlier, for the `guess` call.  So, kudos to you both and thank you for the software!

```
diff --git a/src/frame-writer.cpp b/src/frame-writer.cpp
index bebaa7b..e5e6919 100644
--- a/src/frame-writer.cpp
+++ b/src/frame-writer.cpp
@@ -642,7 +642,9 @@ FrameWriter::FrameWriter(const FrameWriterParams& _params) :
   
   // Preparing the data concerning the format and codec,
   // in order to write properly the header, frame data and end of file.
-  this->outputFmt = av_guess_format(NULL, params.file.c_str(), NULL);
+  this->outputFmt = av_guess_format(
+          params.file_format.empty() ? NULL : params.file_format.c_str(),
+       params.file.c_str(), NULL);
   if (!outputFmt)
     {
       std::cerr << "Failed to guess output format for file " << params.file << std::endl;
```

**Comment by Jamedjo** [comment]
I came across this issue looking to write to stdout so I could have ffmpeg write to a video loopback, but then realized we could support that directly. I've built upon #42 and opened https://github.com/ammen99/wf-recorder/pull/43 adding support for `libavdevice` and setting a custom output format with `--muxer`.
