### ISSUE TITLE
releases

### ISSUE THREAD

**Issue by shibumi** [ammen99/wf-recorder#41]
Hi could you please schedule a release for wf-recorder? I would like to package this for the official arch linux repositories. You get bonus points if you provide a gpg key to sign the release.

**Comment by kaihendry** [comment]
Please cut a release! =)

**Comment by zdykstra** [comment]
It'd be great to see a new release as well, so that this can be packaged for Void Linux!

**Comment by ammen99** [comment]
https://github.com/ammen99/wf-recorder/releases/tag/v0.2

Reopen the issue if I delay too much the next time :)
