### ISSUE TITLE
dmabuf-export support

### ISSUE THREAD

**Issue by emersion** [ammen99/wf-recorder#45]
When using GPU encoding, this prevents a roundtrip to the main memory.

**Comment by ammen99** [comment]
I feel this is borderline out-of-scope. I will review & merge patches though.

**Comment by ddevault** [comment]
Bump. wf-recorder leaves a lot of performance on the table and recording at 4K can be very painful with screencopy.

**Comment by emersion** [comment]
VA-API example: https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/vaapi_encode.c

**Comment by ammen99** [comment]
Fixed in #206, all work is done on the GPU.
