### ISSUE TITLE
vaapi: encoder requires avcodec_send_frame() API, empty file

### ISSUE THREAD

**Issue by edrex** [ammen99/wf-recorder#46]
When attempting to use a VAAPI encoder I get `This encoder requires using the avcodec_send_frame() API.` spam.

https://termbin.com/snrr

I can capture using VAAPI encoding in ffmpeg just fine:

https://termbin.com/81hi

Source build of latest master, Arch with ffmpeg version n4.2

`lspci: 00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)`

**Comment by ammen99** [comment]
I think this is because we're using ffmpeg 3.0 APIs for the time being, and your build may be a bit "too modern". Eventually we'll migrate to 4.0 APIs.

**Comment by edrex** [comment]
thanks for quick response. How can I produce a build against ffmpeg 3 under arch? https://aur.archlinux.org/packages/wf-recorder-git/ seems to pull in a 4.x package. Is there some flag to set or etc?

**Comment by ammen99** [comment]
Hm, I am actually not sure. I am using 4.1 myself, so it should work.

**Comment by edrex** [comment]
i was wondering if it might be a different code path for my graphics hw. i915 driver.

**Comment by ammen99** [comment]
Potentially yes. Does non-vaapi recording work fine?

**Comment by edrex** [comment]
Yes, just without VAAPI it uses > 50% of my 8 cores (vs ~%3 of one core with ffmpeg kmsgrab + vaapi, not sure how much of that is due to using dmabuf).

![Screenshot-2019-08-24-12:03:48](https://user-images.githubusercontent.com/14615/63641830-95498580-c669-11e9-9adc-ddee929e7815.png)

**Comment by ammen99** [comment]
Have you tried other VAAPI codecs?

**Comment by soreau** [comment]
@edrex Does [this patch](http://ix.io/1Tmf) help?

**Comment by edrex** [comment]
@soreau that fixed it, thanks!

**Comment by soreau** [comment]
Great, I'll send a PR.

**Comment by edrex** [comment]
For comparison, with VAAPI it's using ~70% of two cores, so it seems the copy overhead is still pretty significant
![Screenshot-2019-08-24-14:19:34](https://user-images.githubusercontent.com/14615/63642847-93d48900-c67a-11e9-898a-83266ed92926.png)

**Comment by ammen99** [comment]
The PR by @soreau has been merged: #47
