### ISSUE TITLE
Fix arch package | dependencies missing

### ISSUE THREAD

**Issue by Marteon** [ammen99/wf-recorder#48]
The [aur package](https://aur.archlinux.org/packages/wf-recorder-git/) failes compiling because the `opencl-headers` where missing on my system.

The package needs to depend on `opencl-headers`

Sorry I can't comment this in the aur because my account is borked.

**Comment by ammen99** [comment]
Can you post the exact errors? The OpenCL things should only be optional.

**Comment by Marteon** [comment]
I am confused.
When viewing the package on the aur website `opencl-headers` does not show up as dependecie. But when downloading the `PKGBUILD` the `opencl-headers` are listed as dependecie.

After removing the headers `yay` complained that dependecies are missing but didn't install them automatically.

It seems that this is a problem on my side. Closing.
