### ISSUE TITLE
How to stop?

### ISSUE THREAD

**Issue by n73red** [ammen99/wf-recorder#49]
I launch 
bindsym $mod+Shift+Print exec wf-recorder -g "$(slurp)" 
how to stop?

**Comment by ammen99** [comment]
Send SIGINT to the process.

**Comment by n73red** [comment]
this breaks the recordable file and then it is impossible to play it! in fact wf-recorder -g "$ (slurp)" works only from the terminal and ends correctly with the usual Ctrl + c ...
how to assign this to hotkeys? and how to complete correctly so that the recording file does not break?

**Comment by ammen99** [comment]
Ctrl-C is literally SIGINT, are you killing wf-recorder with the correct signal?
Also note I am not using Sway and I do not know how to set this up. But some guys have shared their configurations here: https://github.com/ammen99/wf-recorder/pull/31

Hope this helps.

**Comment by n73red** [comment]
#31 excellent - it works, thanks
