### ISSUE TITLE
wf-recorder might end up trying to encode odd widths/heights if display scaling isn't an integer

### ISSUE THREAD

**Issue by mortie** [ammen99/wf-recorder#55]
I have a 4k screen with 1.5x scaling, because stuff is too small at 1x and too big at 2x. Since wf-recorder deals with regions in logical units, even though it makes sure the logical region has an even width and height, that width/height times 1.5 might end up odd. For example, if I provide a 663x590 region, wf-recorder will change that to 664x590, and then the region that's actually captured will be (664\*1.5)x(590\*1.5) which is 996x885.

I think the best way to fix this would be to translate from logical units to physical units as soon as possible, and then do all modifications on those physical units.

**Comment by Eluminae** [comment]
Hello there!
I'd like to know if there is still works on this issue. Got the same project so I can't really use regioned records cause it will not work 1/2 times.
It is in pipes ? :angel:

**Comment by ammen99** [comment]
@Eluminae, there is a pull request at #56 but I have requested changes since I think the approach there is a hack which is not guaranteed to work AFAICT.

**Comment by mortie** [comment]
Yeah, I didn't take the time to look deeper into it, so I kind of just dropped it. The code generally works though, so cloning https://github.com/mortie/wf-recorder will give you a version of wf-recorder which (in practice) works consistently on HiDPI. It's a few commits behind at this point though.

Now, regarding whether it's guaranteed to work or not; your criticism was that the screencopy protocol says that 'The client should then create a buffer with the provided attributes, and send a "copy" request'. The attributes in question are format, width, height and stride. Looking at my code, that's actually what it does: it creates the `wl_buffer` with `buffer.wl_buffer = create_shm_buffer(format, width, height, stride, &buffer.data);`, where format, width, height and stride are just the values we got straight from the wlr_screencopy frame event. It's only the values in the `wf_buffer` instances which are sometimes modified. I think my approach is OK according to the screencopy protocol.

I should've written this back in october, but, well, work and life got in the way and I forgot about it.
