### ISSUE TITLE
Can't record to v4l loopback

### ISSUE THREAD

**Issue by lovesegfault** [ammen99/wf-recorder#58]
Attempting to record to the v4l2 loopback I get the following error:
```
❯ ./build/wf-recorder --muxer=v4l2 --codec=rawvideo --file=/dev/video5
selected region 0 0 0 0
Choosing pixel format bgr0
Output #0, video4linux2,v4l2, to '/dev/video5':
    Stream #0:0: Unknown: none (rawvideo)
avio_open failed
```

**Comment by soreau** [comment]
It could be a permissions problem, is your user part of the video group?

**Comment by lovesegfault** [comment]
@soreau Yep:
```
❯ groups
wheel video kvm input lpadmin systemd-journal systemd-coredump portage plugdev lxd lovesegfault
```

**Comment by soreau** [comment]
Also you need to have `v4l2loopback` kernel module loaded which will create a device node /dev/video#.

**Comment by lovesegfault** [comment]
@soreau Got it to work after reloading the module!

**Comment by xd003** [comment]
Hello, i am facing this same issue, can you please let me know how to reload that module, thanks

**Comment by unique-EJ** [comment]
> [@soreau](https://github.com/soreau) Got it to work after reloading the module!

@soreau Was the command `# modprobe v4l2loopback`? (run as the root user)

That has not worked in my system.
