### ISSUE TITLE
Detect output when using slurp 

### ISSUE THREAD

**Issue by zajca** [ammen99/wf-recorder#6]
Don't know if this is possible but would be great to detect output when slurp is used.

Or even record multiple output at once, for example grim can make screenshot from area including multiple outputs when using slurp.

**Comment by ammen99** [comment]
Recording multiple outputs is possible, yes, but I am not sure it will work very well. First of all, different outputs can have different refresh rates. Frames might come at different times even if the refresh rate is the same. Plus, we'll need to manually compose the buffers together to present a single big buffer to ffmpeg. So except if I'm wrong I don't think multi-output-recording will be very useful.

About detecting which output, yes, this makes sense. I'll see what I can do.

**Comment by ammen99** [comment]
This was fixed in #19. Reopen if something doesn't work.
