### ISSUE TITLE
Streaming is broken?

### ISSUE THREAD

**Issue by colemickens** [ammen99/wf-recorder#60]
I don't know how to write a good bug report for this unfortunately. The ffmpeg bits seem to startup, but Twitch and YouTube either give a weird cryptic error that is barely noticeable from nothing at all, or nothing at all.

This worked at one point. Can anyone else confirm or deny that it is still working for them? (I'm on HEAD of wlroots and sway and wf-recorder, just as a heads up)

**Comment by ammen99** [comment]
It works for me. Can you try to bisect and see which commit broke it?

**Comment by colemickens** [comment]
Never mind, it's working with Twitch, not sure if I ever have had anything work with YT.
