### ISSUE TITLE
wf-recorder debian dist dependence

### ISSUE THREAD

**Issue by mh4nx7net** [ammen99/wf-recorder#61]
here is who need dependence for debian dist like ubuntu ect
#apt install lib{av{util,codec,format,device},swscale}-dev ocl-icd-opencl-dev

iam sway user 
but litle confuse when don't know where i can get swaygrab for my screenrecord app.
is there who have a way ?
alternatively i use wf-recorder for my wayland compositor thanks

**Comment by ammen99** [comment]
Thanks for the tip, I added the dependencies to https://github.com/ammen99/wf-recorder/wiki/Dependencies-on-different-distributions

I don't understand your question. Can you elaborate? Swaygrab has nothing to do with wf-recorder.

**Comment by mh4nx7net** [comment]
cancel, no thanks dude.
this should not be the problem. coz i am asking about swaygrab on wf-recorder channel hehe.
btw nice for your app, you help me alot

**Comment by ammen99** [comment]
Okay, so if there is no actual problem with wf-recorder, I'll close the issue.
