### ISSUE TITLE
Make pulse dependency optional

### ISSUE THREAD

**Issue by erikvanhamme** [ammen99/wf-recorder#66]
Already done for wf-shell.
Suggest the same approach as in this commit:
https://github.com/WayfireWM/wf-shell/commit/d319b01dd4b0b5b1a1d1ed84308c437bd9ed6857

**Comment by Himmalerin** [comment]
`-Dpulse=disabled` doesn't entirely work. Meson prints out
```
Dependency libpulse-simple skipped: feature pulse disabled
```
as I imagine it should, but when attempting to build with ninja it still fails:
```
ninja: job failed: c++ -Iwf-recorder@exe -I. -I.. -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++11 -g -Wno-deprecated-declarations -O3 -march=native -pthread -MD -MQ 'wf-recorder@exe/src_main.cpp.o' -MF 'wf-recorder@exe/src_main.cpp.o.d' -o 'wf-recorder@exe/src_main.cpp.o' -c ../src/main.cpp
In file included from ../src/main.cpp:21:
../src/pulse.hpp:4:10: fatal error: pulse/simple.h: No such file or directory
    4 | #include <pulse/simple.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
ninja: subcommand failed
```
the build commands I'm using are
```
meson -Dpulse=disabled . build
ninja -C build
```

**Comment by ammen99** [comment]
@Himmalerin Thanks, this doesn't work indeed. I haven't caught it since I have pulse on my system. I just pushed a fix for it in master, can you try pulling latest changes and rebuilding?

**Comment by Himmalerin** [comment]
Building off the latest commit worked, thanks for the quick fix!

**Comment by soreau** [comment]
FWIW, you should even need to pass -Dpulse-disabled unless the pulse development files are installed. It should automatically detect pulse isn't present and disable it.
