### ISSUE TITLE
Writing to stdout

### ISSUE THREAD

**Issue by watzon** [ammen99/wf-recorder#67]
Is there a way currently to write to stdout rather than a file?

**Comment by ammen99** [comment]
No, but why would you need to write to the output?

**Comment by watzon** [comment]
For piping purposes mostly

**Comment by rkanati** [comment]
@watzon although the documentation/usage isn't clear, the "path" accepted by `-f` is just an ffmpeg url, so if you want to pipe the recording, you can do something like:
```sh
$ wf-recorder -f pipe:99 -m some_muxer -c some_codec 99>&1 >&2 | pipeline
```
(I think I got this right - you can't use stdout directly because `wf-recorder` prints some stuff to it)

**Comment by ammen99** [comment]
@rkanati Cool, I didn't know this was possible. I don't think we need any special support in wf-recorder in this case._

**Comment by rkanati** [comment]
@ammen99 sure, but changing all of wf-recorder's logging to stderr would be nice.

**Comment by progandy** [comment]
```pipe:99``` might not work if you are unable to create the pipe and supply it to ffmpeg. An alternative in korn, zsh or bash shells is process subsitution:

```bash
./wf-recorder -c rawvideo  -x yuv420p -m avi -f >(ffplay -f avi -)
```
