### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by ubone** [ammen99/wf-recorder#68]
could you explain how wf-rec uses ffmpeg, what the defaults are (ffmpeg or it's own?),
what options are usable, for ex. can it record a lossless x264 video with opus audio?
or basically how to "translate" ffmpeg options I'd use to wf-rec, if applicable at all

**Comment by soreau** [comment]
wf-recorder uses libav. You can specify video codec at runtime, [default_codec](https://github.com/ammen99/wf-recorder/blob/master/meson_options.txt#L1) at build time and parameter options but audio is currently hard coded to `aac` [here](https://github.com/ammen99/wf-recorder/blob/master/src/frame-writer.cpp#L238). An option to change audio codec could be added, patches welcome. See [the manpage](https://github.com/ammen99/wf-recorder/blob/master/manpage/wf-recorder.1.scd) for more information.

**Comment by ammen99** [comment]
The manpage and/or the output of `--help` is the best place to see what the available options are. I think we leave most of the things for ffmpeg to autodetect, the only thing that we set by default is the codec to use(`libx264`).
