### ISSUE TITLE
ioctl(VIDIOC_G_FMT): Invalid argument

### ISSUE THREAD

**Issue by jdonofrio728** [ammen99/wf-recorder#70]
This is probably an issue on my side, but I'm seeing the following error when attempting to create a v4l2 loop device:
```
$ ./wf-recorder --muxer=v4l2 --codec=rawvideo --file=/dev/video2 -o DP-1
selected region 0 0 0 0
Choosing pixel format bgr0
Output #0, video4linux2,v4l2, to '/dev/video2':
    Stream #0:0: Unknown: none (rawvideo)
[video4linux2,v4l2 @ 0x7f74b0000cc0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[video4linux2,v4l2 @ 0x7f74b0000cc0] ioctl(VIDIOC_G_FMT): Invalid argument
Failed to write file header
Invalid argument
```

From what I was able to gather it sounds like there may be a driver issue or something missing on my system. Anyone have any ideas on what may be going on?

I'm running the commit `ccbd0c7` which is latest as of today.

**Comment by soreau** [comment]
Do you have v4l2loopback kernel module loaded? Loading it will create a device node /dev/video# for you to use.

**Comment by jdonofrio728** [comment]
Yep, that was the issue. I picked it up from the AUR and its working now. Thanks @soreau for the quick response
