### ISSUE TITLE
request for features

### ISSUE THREAD

**Issue by mh4nx7net** [ammen99/wf-recorder#72]
i have a idea like an common another screen recorder.
which has feature where the app self can automaticaly give a webcam record as well as input sound, on linux like from source /dev/video0

i've try'd with code with ffmpeg addition but still rough. i hope you as dev of wf-rec, can add this as nativel plugin or feature in future!! GANBATTE !!

**Comment by soreau** [comment]
There's a command on the [wiki](https://github.com/WayfireWM/wayfire/wiki/Tutorial) that shows you how to show webcam in a window using gstreamer:
```
gst-launch-1.0 -v v4l2src device=/dev/video0 ! glimagesink
```
and you can record audio with the `-a` option of wf-recorder.

**Comment by mh4nx7net** [comment]
wow that's great
