### ISSUE TITLE
Is it possible to record internal audio not microphone?

### ISSUE THREAD

**Issue by Ordoviz** [ammen99/wf-recorder#76]
When I run `wf-recorder -a` my laptop microphone gets recorded. The manual suggest to run `pactl list sinks` which gives *alsa_output.pci-0000_00_1b.0.analog-stereo* in my case. But `wf-recorder -a alsa_output.pci-0000_00_1b.0.analog-stereo` still records my microphone and *Using PulseAudio device: default* gets printed to the console.

**Comment by soreau** [comment]
See issue #39.

**Comment by Ordoviz** [comment]
Thanks a lot! Either `wf-recorder -a0` or `wf-recorder --audio=0` does what I want.
