### ISSUE TITLE
Allow downscaling resolution of video recording

### ISSUE THREAD

**Issue by maximbaz** [ammen99/wf-recorder#77]
When I record my 4k screen to `video4linux2`, wf-recorder uses 100% CPU. I want to record full screen, but I'm willing to sacrifice resolution, and record it in Full HD, if that helps reducing CPU usage. If I record a part of the screen of 1920x1200 resolution, wf-recorder only consumes ~25% CPU. I'd like to be able to tell wf-recorder to record full screen but downscale it to Full HD, so that hopefully CPU usage is not that high.

**Comment by ammen99** [comment]
I think you are already aware of `https://github.com/schauveau/wf-recorder-x`. I do not know why the person who wrote that code there hasn't opened PRs to merge his work.

@scauveau Any plans for bringing your work to upstream?

**Comment by maximbaz** [comment]
Yes, I wanted to try that project but sadly it was forked before streaming to `v4l2loopback` was implemented, and quick attempt to rebase on master failed with some conflicts (I didn't loop much into it).

**Comment by ammen99** [comment]
One workaround is to just lower the resolution of your screen. I know this isn't ideal but since you're already sacrificing on quality ...

**Comment by maximbaz** [comment]
Good point, and this reduced CPU usage to 50%

**Comment by varac** [comment]
@ammen99: Can you think of any other possible CPU load improvement besides reducing screen resolution ?

**Comment by soreau** [comment]
@varac You can use the gpu to encode the video using vaapi. Refer to the [README](https://github.com/ammen99/wf-recorder/blob/master/README.md) for more information.

**Comment by truesilver92** [comment]
If we change the scope of the project to just being an ffmpeg input device then you will already have this capability as an ffmpeg filter https://github.com/ammen99/wf-recorder/issues/139

**Comment by hholst80** [comment]
In case anyone runs across this issue the solution is this (no need to use the fork):

Suppose i have a 4k source and want to save the recording in full 1080p:

```sh
wf-recorder -f test-vaapi.mp4 -c h264_vaapi -a -F scale_vaapi=format=nv12:w=1920:h=1080
```
