### ISSUE TITLE
Cant kill process when using libvpx-vp9 codec

### ISSUE THREAD

**Issue by apiraino** [ammen99/wf-recorder#80]
Hi,

I can't CTRL+C wf-recorder when using the VP9 codec, I need to manually kill the process.

`$ wf-recorder -c libvpx-vp9 -f ~/tmp/recording.webm`

Using VP8 works fine: `$ wf-recorder -c libvpx -f ~/tmp/recording.webm`

Opinion on this behaviour?

thanks

**Comment by ammen99** [comment]
This is not caused by wf-recorder, my best guess is that the codec somehow interferes with SIGINT? Though I can't think of why it does that.

**Comment by apiraino** [comment]
if it's of any help:

```
$ ffmpeg --version
ffmpeg version 4.1.4-1build2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.2.1-4ubuntu1)
```

and I'm using a wf-recorder 0.2 of some kind (self compiled from master two months ago)

**Comment by ammen99** [comment]
Have you tried using ffmpeg directly in X11,with this codec?

**Comment by apiraino** [comment]
Good idea! I tried these two commands (either x11 and wayland).

`ffmpeg -i input.file -c:v libvpx -f webm output.file`
-> ctrl+c: immediate close

`ffmpeg -i input.file -c:v libvpx-vp9 -f webm output.file`
-> ctrl+c: close after 2 or 3 seconds

I suspect that wf-recorder sends a signal that is ignored (?). No idea.

Nothing @ammen99 you see worth investigating? At least documenting?

**Comment by ammen99** [comment]
@apiraino I am not familiar with all the codecs that ffmpeg uses, and since it works with most of them I'd say it is not our problem.

We can add a workaround probably, but I am not sure how.

**Comment by apiraino** [comment]
I see your point. Well, in this case feel free to close this issue if you don't see anything actionable or leave it open as a reminder if you plan to work on this.

Thank you

**Comment by apiraino** [comment]
ok after some more tests, I understood that the SIGINT is actually received but it takes a lot of time (like 17 seconds on a 8-core i7-8550U) to wf-recorder to be able to close the encoding.

If I manually put in background and kill the process, the resulting file is corrupt. That was a hint that I just needed to wait and let wf-recorder do its job.

Weird, to say the least :-)

**Comment by ammen99** [comment]
Oh that makes sense. The thing is, wf-recorder just queues frames to the encoder, and we don't know when it will be ready. Upon ctrl-c, it just stops feeding new frames and waits until the encoder is done.

Good that you found the reason :)

**Comment by apiraino** [comment]
> and we don't know when it will be ready.

Would it make sense to print something when wf-recorder receives the SIGINT and waits for the encoder to finish (also something like "Waiting for encoding to finish ...")? Just to let know the user knows what's happening.
As a user, I'm probably hitting a usability corner case :) but I wouldn't mind wf-recorder letting me know that I should not kill it.

**Comment by ammen99** [comment]
Yep, that's a good idea.
