### ISSUE TITLE
flickering mouse cursor/pointer artifacts in video

### ISSUE THREAD

**Issue by dllu** [ammen99/wf-recorder#81]
Running `wf-recorder` causes my mouse pointer to leave behind a flickering trail of artifacts, and this also shows up in the video. For some reason, running `wf-recorder` also causes the audio on my computer to stutter.

The flickering cursor artifacts immediately stops once I stop `wf-recorder`.

Video of problem: https://www.youtube.com/watch?v=UNijGlf_JtU 

The problem exists in both xwayland windows (e.g. firefox, above) and in true Wayland windows (e.g. Alacritty, below).

* wf-recorder: `wf-recorder-git-r109.418f277`
* Window manager: `sway version 1.4-3078f232 (Apr  7 2020, branch 'master')`
* wlroots: `0.10.0.r59.g1fa9e020-1`

* OS: Arch Linux
* GPU: AMD Radeon 5700 XT
* GPU driver: mesa 20.0.4
* CPU: AMD Ryzen 9 3900X
* Kernel: Linux 5.6.0-1-mainline

The problem has also existed for many months.

**Comment by ammen99** [comment]
Hi, this is most likely a problem in wlroots/sway because wf-recorder just grabs the image from Sway (and forces software rendering of cursors), but that is something the compositor does.

Open an issue in their issue tracker, though we could also keep this one open until the bug is resolved.

**Comment by dllu** [comment]
Thanks! Is there a way to disable capturing the cursor at all in wf-recorder?

**Comment by ammen99** [comment]
Currently, no.

**Comment by ammen99** [comment]
Except if you don't patch it of course, should be easy since the screencopy protocol has `overlay_cursor` flag. That flag is however not guaranteed to always work.

**Comment by dllu** [comment]
The flickering cursor bug has magically disappeared after being there for months. Hooray!

**Comment by HydraOrc** [comment]
Disabling "Radeon Enhanced Sync" should work
