### ISSUE TITLE
Put OpenCL dependency behind a conditional

### ISSUE THREAD

**Issue by lanodan** [ammen99/wf-recorder#87]
in `meson.build`, you currently have the following:
```meson
opencl = dependency('OpenCL', required : get_option('opencl'))
```

It should be written like so:
```meson
if not get_option('opencl').disabled()
  opencl = dependency('OpenCL', required : true)
else
  opencl = disabler()
endif
```

This way it is possible to build a package that doesn't depends on OpenCL on a build-machine which has it. No pull request done because without #66 being fixed I can't test it on my machine.

**Comment by soreau** [comment]
You should be able to build without opencl by passing `-Dopencl=disabled`.

disabler() is not what you want because including a dep that is set to disabler() disables the target, so the executable would not be built in this case.

**Comment by soreau** [comment]
For reference: https://mesonbuild.com/Build-options.html#features
