### ISSUE TITLE
Specify codec options from command line

### ISSUE THREAD

**Issue by foxpy** [ammen99/wf-recorder#9]
#7 allows to specify codec from command line. But user still has no ability to specify codec options. Currently, for `libx264` these parameters are set: crf 20, tune zerolatency, preset ultrafast. For any other codec default parameters from `libavcodec` are being supplied.

I think the best is to include a list of predefined codecs (I have specified them [here](https://github.com/ammen99/wf-recorder/issues/2#issuecomment-472830274)) and provide an interface for users to adjust codec options for their needs. That's of course not a complete list, but these codecs are first to come up in my mind.

**Comment by ammen99** [comment]
I would rather just add an argument for the user to list any codec option they'd like to use. So adding options like `-p codec_opt=value`. And we can just use the options I have hardcoded for libx264/x265.

**Comment by ammen99** [comment]
Hm, do most codecs support YUV420 input format?

**Comment by foxpy** [comment]
> do most codecs support YUV420 input format?

Yes, they do. Buy the way, YUV420 is the most common format.
