### ISSUE TITLE
Force 60fps recordings

### ISSUE THREAD

**Issue by kamiyaa** [ammen99/wf-recorder#96]
I was wondering if it is possible to force `wf-recorder` to record at a consistent 60fps? (ie. an ffmpeg parameter)
It seems right now, `wf-recorder` records at a variable framerate.
This causes programs like `kdenlive` to render videos recorded by `wf-recorder` at a very low framerate.

Output of mediainfo, ran with `wf-recorder -f file.mp4`
```
...
Duration                                 : 11 s 545 ms
Bit rate                                 : 4 007 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 13.253 FPS
Minimum frame rate                       : 0.315 FPS
Maximum frame rate                       : 106.257 FPS
Original frame rate                      : 60.000 FPS
...
```
Thanks!

**Comment by ammen99** [comment]
Since a recent commit we started to not request frames continuously from the compositor. Is the situation better with the 0.2.1 release instead of master?

Btw, we can't really force 60fps because the frames are sent by the compositor. And the compositor rarely works at exactly 60fps, but rather always a bit more or less.

**Comment by jiayiizhao** [comment]
Yes, it seems 0.2.1 works better. Mediainfo reports 59fps.

I also realized I can force 60fps on kdenlive renders, but even then, 0.2.1 is still a bit smoother than master

**Comment by ammen99** [comment]
Alright, we could add a flag to control this behavior. Thanks for reporting it.

**Comment by kamiyaa** [comment]
> Yes, it seems 0.2.1 works better. Mediainfo reports 59fps.
>
> I also realized I can force 60fps on kdenlive renders, but even then, 0.2.1 is still a bit smoother than master
Wrong account, oops xd

**Comment by ammen99** [comment]
You can use the new `-D` command line flag to make wf-recorder continuously request frames from the compositor, it should achieve (near-)maximal frame rate
