### ISSUE TITLE
Can't record application audio

### ISSUE THREAD

**Issue by PonasKovas** [ammen99/wf-recorder#97]
OS: ArchLinux

I need to record my screen both with my application audio and mic input.

I tried specifiyng all devices with `-a` flag, but none of them worked, and the virtual sink way didn't work too, all I hear is my mic input and not applications audio.

**Comment by soreau** [comment]
Have you tried just -a with no arguments? Have you read what the wiki says about this?

**Comment by PonasKovas** [comment]
yes, just -a records only mic input too. I did read the wiki

**Comment by soreau** [comment]
Does it make a difference if you try --audio <device>?

**Comment by PonasKovas** [comment]
That's what I was doing too.
```
> pacmd list-sources | grep "name:"
	name: <alsa_output.pci-0000_00_1b.0.analog-stereo.monitor>
	name: <alsa_input.pci-0000_00_1b.0.analog-stereo>
> wf-recorder -a "alsa_output.pci-0000_00_1b.0.analog-stereo.monitor"
> wf-recorder -a "alsa_input.pci-0000_00_1b.0.analog-stereo"
```
neither of these two commands recorded application audio

**Comment by soreau** [comment]
Maybe related to #39

**Comment by PonasKovas** [comment]
if I use `=` I don't get any audio at all

**Comment by PonasKovas** [comment]
okay it finally worked.
```
wf-recorder --audio="alsa_output.pci-0000_00_1b.0.analog-stereo.monitor"
```
maybe you should consider using a different library for parsing command line arguments and provide more examples in the wiki, because at the beginning i specified the devices with `<>` brackets because that's how they we're outputted by the `pacmd list-sources` command.

**Comment by soreau** [comment]
Patches and wiki contributions welcome.
